// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.datamodel;

@kotlin.jvm.JvmName("-initializeblockWord")
public inline fun blockWord(block: com.bugenzhao.mnga.protos.datamodel.BlockWordKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.BlockWord =
  com.bugenzhao.mnga.protos.datamodel.BlockWordKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.BlockWord.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `BlockWord`
 */
public object BlockWordKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.datamodel.BlockWord.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.BlockWord.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.datamodel.BlockWord = _builder.build()

    /**
     * `string word = 1;`
     */
    public var word: kotlin.String
      @kotlin.jvm.JvmName("getWord")
        get() = _builder.word
      @kotlin.jvm.JvmName("setWord")
        set(value) {
        _builder.word = value
      }
    /**
     * `string word = 1;`
     */
    public fun clearWord() {
      _builder.clearWord()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.BlockWord.copy(block: `com.bugenzhao.mnga.protos.datamodel`.BlockWordKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.BlockWord =
  `com.bugenzhao.mnga.protos.datamodel`.BlockWordKt.Dsl._create(this.toBuilder()).apply { block() }._build()

