// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface BlockWordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BlockWord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string word = 1;</code>
   * @return The word.
   */
  java.lang.String getWord();
  /**
   * <code>string word = 1;</code>
   * @return The bytes for word.
   */
  com.google.protobuf.ByteString
      getWordBytes();
}
