// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface CategoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Category)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .Forum forums = 3;</code>
   */
  java.util.List<com.bugenzhao.mnga.protos.datamodel.Forum> 
      getForumsList();
  /**
   * <code>repeated .Forum forums = 3;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.Forum getForums(int index);
  /**
   * <code>repeated .Forum forums = 3;</code>
   */
  int getForumsCount();
  /**
   * <code>repeated .Forum forums = 3;</code>
   */
  java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.ForumOrBuilder> 
      getForumsOrBuilderList();
  /**
   * <code>repeated .Forum forums = 3;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.ForumOrBuilder getForumsOrBuilder(
      int index);
}
