// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface ConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Configuration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Path to an App-local writable directory.
   * </pre>
   *
   * <code>string document_dir_path = 1;</code>
   * @return The documentDirPath.
   */
  java.lang.String getDocumentDirPath();
  /**
   * <pre>
   * Path to an App-local writable directory.
   * </pre>
   *
   * <code>string document_dir_path = 1;</code>
   * @return The bytes for documentDirPath.
   */
  com.google.protobuf.ByteString
      getDocumentDirPathBytes();
}
