// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

/**
 * Protobuf type {@code Configuration}
 */
@com.google.protobuf.Generated
public final class Configuration extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Configuration)
    ConfigurationOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Configuration");
  }
  // Use Configuration.newBuilder() to construct.
  private Configuration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Configuration() {
    documentDirPath_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_Configuration_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_Configuration_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_Configuration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bugenzhao.mnga.protos.datamodel.Configuration.class, com.bugenzhao.mnga.protos.datamodel.Configuration.Builder.class);
  }

  public static final int DOCUMENT_DIR_PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object documentDirPath_ = "";
  /**
   * <pre>
   * Path to an App-local writable directory.
   * </pre>
   *
   * <code>string document_dir_path = 1;</code>
   * @return The documentDirPath.
   */
  @java.lang.Override
  public java.lang.String getDocumentDirPath() {
    java.lang.Object ref = documentDirPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      documentDirPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Path to an App-local writable directory.
   * </pre>
   *
   * <code>string document_dir_path = 1;</code>
   * @return The bytes for documentDirPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDocumentDirPathBytes() {
    java.lang.Object ref = documentDirPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      documentDirPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(documentDirPath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, documentDirPath_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(documentDirPath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, documentDirPath_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bugenzhao.mnga.protos.datamodel.Configuration)) {
      return super.equals(obj);
    }
    com.bugenzhao.mnga.protos.datamodel.Configuration other = (com.bugenzhao.mnga.protos.datamodel.Configuration) obj;

    if (!getDocumentDirPath()
        .equals(other.getDocumentDirPath())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOCUMENT_DIR_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getDocumentDirPath().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.datamodel.Configuration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bugenzhao.mnga.protos.datamodel.Configuration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Configuration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Configuration)
      com.bugenzhao.mnga.protos.datamodel.ConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_Configuration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_Configuration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bugenzhao.mnga.protos.datamodel.Configuration.class, com.bugenzhao.mnga.protos.datamodel.Configuration.Builder.class);
    }

    // Construct using com.bugenzhao.mnga.protos.datamodel.Configuration.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      documentDirPath_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_Configuration_descriptor;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.Configuration getDefaultInstanceForType() {
      return com.bugenzhao.mnga.protos.datamodel.Configuration.getDefaultInstance();
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.Configuration build() {
      com.bugenzhao.mnga.protos.datamodel.Configuration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.Configuration buildPartial() {
      com.bugenzhao.mnga.protos.datamodel.Configuration result = new com.bugenzhao.mnga.protos.datamodel.Configuration(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bugenzhao.mnga.protos.datamodel.Configuration result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.documentDirPath_ = documentDirPath_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bugenzhao.mnga.protos.datamodel.Configuration) {
        return mergeFrom((com.bugenzhao.mnga.protos.datamodel.Configuration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bugenzhao.mnga.protos.datamodel.Configuration other) {
      if (other == com.bugenzhao.mnga.protos.datamodel.Configuration.getDefaultInstance()) return this;
      if (!other.getDocumentDirPath().isEmpty()) {
        documentDirPath_ = other.documentDirPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              documentDirPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object documentDirPath_ = "";
    /**
     * <pre>
     * Path to an App-local writable directory.
     * </pre>
     *
     * <code>string document_dir_path = 1;</code>
     * @return The documentDirPath.
     */
    public java.lang.String getDocumentDirPath() {
      java.lang.Object ref = documentDirPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        documentDirPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Path to an App-local writable directory.
     * </pre>
     *
     * <code>string document_dir_path = 1;</code>
     * @return The bytes for documentDirPath.
     */
    public com.google.protobuf.ByteString
        getDocumentDirPathBytes() {
      java.lang.Object ref = documentDirPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        documentDirPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Path to an App-local writable directory.
     * </pre>
     *
     * <code>string document_dir_path = 1;</code>
     * @param value The documentDirPath to set.
     * @return This builder for chaining.
     */
    public Builder setDocumentDirPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      documentDirPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Path to an App-local writable directory.
     * </pre>
     *
     * <code>string document_dir_path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDocumentDirPath() {
      documentDirPath_ = getDefaultInstance().getDocumentDirPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Path to an App-local writable directory.
     * </pre>
     *
     * <code>string document_dir_path = 1;</code>
     * @param value The bytes for documentDirPath to set.
     * @return This builder for chaining.
     */
    public Builder setDocumentDirPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      documentDirPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Configuration)
  }

  // @@protoc_insertion_point(class_scope:Configuration)
  private static final com.bugenzhao.mnga.protos.datamodel.Configuration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bugenzhao.mnga.protos.datamodel.Configuration();
  }

  public static com.bugenzhao.mnga.protos.datamodel.Configuration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Configuration>
      PARSER = new com.google.protobuf.AbstractParser<Configuration>() {
    @java.lang.Override
    public Configuration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Configuration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Configuration> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.Configuration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

