// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface ErrorMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErrorMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string info = 2;</code>
   * @return The info.
   */
  java.lang.String getInfo();
  /**
   * <code>string info = 2;</code>
   * @return The bytes for info.
   */
  com.google.protobuf.ByteString
      getInfoBytes();

  /**
   * <code>string detailed = 3;</code>
   * @return The detailed.
   */
  java.lang.String getDetailed();
  /**
   * <code>string detailed = 3;</code>
   * @return The bytes for detailed.
   */
  com.google.protobuf.ByteString
      getDetailedBytes();
}
