// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface NotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Notification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 9;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 9;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.Notification.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.Notification.Type type = 1;</code>
   * @return The type.
   */
  com.bugenzhao.mnga.protos.datamodel.Notification.Type getType();

  /**
   * <code>.User other_user = 2;</code>
   * @return Whether the otherUser field is set.
   */
  boolean hasOtherUser();
  /**
   * <code>.User other_user = 2;</code>
   * @return The otherUser.
   */
  com.bugenzhao.mnga.protos.datamodel.User getOtherUser();
  /**
   * <code>.User other_user = 2;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.UserOrBuilder getOtherUserOrBuilder();

  /**
   * <pre>
   * ID of our post.
   * </pre>
   *
   * <code>.PostId post_id = 3;</code>
   * @return Whether the postId field is set.
   */
  boolean hasPostId();
  /**
   * <pre>
   * ID of our post.
   * </pre>
   *
   * <code>.PostId post_id = 3;</code>
   * @return The postId.
   */
  com.bugenzhao.mnga.protos.datamodel.PostId getPostId();
  /**
   * <pre>
   * ID of our post.
   * </pre>
   *
   * <code>.PostId post_id = 3;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.PostIdOrBuilder getPostIdOrBuilder();

  /**
   * <pre>
   * ID of other's post.
   * </pre>
   *
   * <code>.PostId other_post_id = 4;</code>
   * @return Whether the otherPostId field is set.
   */
  boolean hasOtherPostId();
  /**
   * <pre>
   * ID of other's post.
   * </pre>
   *
   * <code>.PostId other_post_id = 4;</code>
   * @return The otherPostId.
   */
  com.bugenzhao.mnga.protos.datamodel.PostId getOtherPostId();
  /**
   * <pre>
   * ID of other's post.
   * </pre>
   *
   * <code>.PostId other_post_id = 4;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.PostIdOrBuilder getOtherPostIdOrBuilder();

  /**
   * <code>.Subject topic_subject = 5;</code>
   * @return Whether the topicSubject field is set.
   */
  boolean hasTopicSubject();
  /**
   * <code>.Subject topic_subject = 5;</code>
   * @return The topicSubject.
   */
  com.bugenzhao.mnga.protos.datamodel.Subject getTopicSubject();
  /**
   * <code>.Subject topic_subject = 5;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.SubjectOrBuilder getTopicSubjectOrBuilder();

  /**
   * <code>uint64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * The page of other's post in the topic.
   * </pre>
   *
   * <code>uint32 page = 7;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <pre>
   * Whether this notification has been read.
   * </pre>
   *
   * <code>bool read = 8;</code>
   * @return The read.
   */
  boolean getRead();
}
