// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.datamodel;

@kotlin.jvm.JvmName("-initializepostAttachment")
public inline fun postAttachment(block: com.bugenzhao.mnga.protos.datamodel.PostAttachmentKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.PostAttachment =
  com.bugenzhao.mnga.protos.datamodel.PostAttachmentKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.PostAttachment.newBuilder()).apply { block() }._build()
/**
 * ```
 * Attachments that have been already uploaded, but not posted yet.
 * ```
 *
 * Protobuf type `PostAttachment`
 */
public object PostAttachmentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.datamodel.PostAttachment.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.PostAttachment.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.datamodel.PostAttachment = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string url = 2;`
     */
    public var url: kotlin.String
      @kotlin.jvm.JvmName("getUrl")
        get() = _builder.url
      @kotlin.jvm.JvmName("setUrl")
        set(value) {
        _builder.url = value
      }
    /**
     * `string url = 2;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }

    /**
     * ```
     * Verification code for posting this attachment.
     * ```
     *
     * `string check = 3;`
     */
    public var check: kotlin.String
      @kotlin.jvm.JvmName("getCheck")
        get() = _builder.check
      @kotlin.jvm.JvmName("setCheck")
        set(value) {
        _builder.check = value
      }
    /**
     * ```
     * Verification code for posting this attachment.
     * ```
     *
     * `string check = 3;`
     */
    public fun clearCheck() {
      _builder.clearCheck()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.PostAttachment.copy(block: `com.bugenzhao.mnga.protos.datamodel`.PostAttachmentKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.PostAttachment =
  `com.bugenzhao.mnga.protos.datamodel`.PostAttachmentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

