// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface PostIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of this post. If `pid` is 0, it's the main floor of
   * </pre>
   *
   * <code>string pid = 1;</code>
   * @return The pid.
   */
  java.lang.String getPid();
  /**
   * <pre>
   * The id of this post. If `pid` is 0, it's the main floor of
   * </pre>
   *
   * <code>string pid = 1;</code>
   * @return The bytes for pid.
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <pre>
   * this `topic`. Otherwise, it's globally unique.
   * </pre>
   *
   * <code>string tid = 2;</code>
   * @return The tid.
   */
  java.lang.String getTid();
  /**
   * <pre>
   * this `topic`. Otherwise, it's globally unique.
   * </pre>
   *
   * <code>string tid = 2;</code>
   * @return The bytes for tid.
   */
  com.google.protobuf.ByteString
      getTidBytes();
}
