// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface PostReplyVerbatimOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostReplyVerbatim)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether this modification can only be appendent due
   * </pre>
   *
   * <code>bool modify_append = 1;</code>
   * @return The modifyAppend.
   */
  boolean getModifyAppend();

  /**
   * <pre>
   * to exceeding of date, or in-place.
   * </pre>
   *
   * <code>string auth = 2;</code>
   * @return The auth.
   */
  java.lang.String getAuth();
  /**
   * <pre>
   * to exceeding of date, or in-place.
   * </pre>
   *
   * <code>string auth = 2;</code>
   * @return The bytes for auth.
   */
  com.google.protobuf.ByteString
      getAuthBytes();

  /**
   * <pre>
   * URL where attachments should be uploaded to.
   * </pre>
   *
   * <code>string attach_url = 3;</code>
   * @return The attachUrl.
   */
  java.lang.String getAttachUrl();
  /**
   * <pre>
   * URL where attachments should be uploaded to.
   * </pre>
   *
   * <code>string attach_url = 3;</code>
   * @return The bytes for attachUrl.
   */
  com.google.protobuf.ByteString
      getAttachUrlBytes();
}
