// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.datamodel;

@kotlin.jvm.JvmName("-initializepost")
public inline fun post(block: com.bugenzhao.mnga.protos.datamodel.PostKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Post =
  com.bugenzhao.mnga.protos.datamodel.PostKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.Post.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `Post`
 */
public object PostKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.datamodel.Post.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.Post.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.datamodel.Post = _builder.build()

    /**
     * `.PostId id = 6;`
     */
    public var id: com.bugenzhao.mnga.protos.datamodel.PostId
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `.PostId id = 6;`
     */
    public fun clearId() {
      _builder.clearId()
    }
    /**
     * `.PostId id = 6;`
     * @return Whether the id field is set.
     */
    public fun hasId(): kotlin.Boolean {
      return _builder.hasId()
    }

    public val PostKt.Dsl.idOrNull: com.bugenzhao.mnga.protos.datamodel.PostId?
      get() = _builder.idOrNull

    /**
     * ```
     * This might be inaccurate if it's from a special topic
     * ```
     *
     * `uint32 floor = 1;`
     */
    public var floor: kotlin.Int
      @kotlin.jvm.JvmName("getFloor")
        get() = _builder.floor
      @kotlin.jvm.JvmName("setFloor")
        set(value) {
        _builder.floor = value
      }
    /**
     * ```
     * This might be inaccurate if it's from a special topic
     * ```
     *
     * `uint32 floor = 1;`
     */
    public fun clearFloor() {
      _builder.clearFloor()
    }

    /**
     * ```
     * details request with other arguments specified.
     * ```
     *
     * `string author_id = 2;`
     */
    public var authorId: kotlin.String
      @kotlin.jvm.JvmName("getAuthorId")
        get() = _builder.authorId
      @kotlin.jvm.JvmName("setAuthorId")
        set(value) {
        _builder.authorId = value
      }
    /**
     * ```
     * details request with other arguments specified.
     * ```
     *
     * `string author_id = 2;`
     */
    public fun clearAuthorId() {
      _builder.clearAuthorId()
    }

    /**
     * `.PostContent content = 3;`
     */
    public var content: com.bugenzhao.mnga.protos.datamodel.PostContent
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `.PostContent content = 3;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * `.PostContent content = 3;`
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }

    public val PostKt.Dsl.contentOrNull: com.bugenzhao.mnga.protos.datamodel.PostContent?
      get() = _builder.contentOrNull

    /**
     * ```
     * The timestamp of the posting.
     * ```
     *
     * `uint64 post_date = 4;`
     */
    public var postDate: kotlin.Long
      @kotlin.jvm.JvmName("getPostDate")
        get() = _builder.postDate
      @kotlin.jvm.JvmName("setPostDate")
        set(value) {
        _builder.postDate = value
      }
    /**
     * ```
     * The timestamp of the posting.
     * ```
     *
     * `uint64 post_date = 4;`
     */
    public fun clearPostDate() {
      _builder.clearPostDate()
    }

    /**
     * ```
     * The number of upvotes.
     * ```
     *
     * `uint32 score = 5;`
     */
    public var score: kotlin.Int
      @kotlin.jvm.JvmName("getScore")
        get() = _builder.score
      @kotlin.jvm.JvmName("setScore")
        set(value) {
        _builder.score = value
      }
    /**
     * ```
     * The number of upvotes.
     * ```
     *
     * `uint32 score = 5;`
     */
    public fun clearScore() {
      _builder.clearScore()
    }

    /**
     * ```
     * The vote state cached from current client before.
     * ```
     *
     * `.VoteState vote_state = 7;`
     */
    public var voteState: com.bugenzhao.mnga.protos.datamodel.VoteState
      @kotlin.jvm.JvmName("getVoteState")
        get() = _builder.voteState
      @kotlin.jvm.JvmName("setVoteState")
        set(value) {
        _builder.voteState = value
      }
    public var voteStateValue: kotlin.Int
      @kotlin.jvm.JvmName("getVoteStateValue")
        get() = _builder.voteStateValue
      @kotlin.jvm.JvmName("setVoteStateValue")
        set(value) {
        _builder.voteStateValue = value
      }
    /**
     * ```
     * The vote state cached from current client before.
     * ```
     *
     * `.VoteState vote_state = 7;`
     */
    public fun clearVoteState() {
      _builder.clearVoteState()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HotRepliesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Hot replies only exist in the main floor.
     * ```
     *
     * `repeated .Post hot_replies = 8;`
     */
     public val hotReplies: com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, HotRepliesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.hotRepliesList
      )
    /**
     * ```
     * Hot replies only exist in the main floor.
     * ```
     *
     * `repeated .Post hot_replies = 8;`
     * @param value The hotReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addHotReplies")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, HotRepliesProxy>.add(value: com.bugenzhao.mnga.protos.datamodel.Post) {
      _builder.addHotReplies(value)
    }
    /**
     * ```
     * Hot replies only exist in the main floor.
     * ```
     *
     * `repeated .Post hot_replies = 8;`
     * @param value The hotReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignHotReplies")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, HotRepliesProxy>.plusAssign(value: com.bugenzhao.mnga.protos.datamodel.Post) {
      add(value)
    }
    /**
     * ```
     * Hot replies only exist in the main floor.
     * ```
     *
     * `repeated .Post hot_replies = 8;`
     * @param values The hotReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllHotReplies")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, HotRepliesProxy>.addAll(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.Post>) {
      _builder.addAllHotReplies(values)
    }
    /**
     * ```
     * Hot replies only exist in the main floor.
     * ```
     *
     * `repeated .Post hot_replies = 8;`
     * @param values The hotReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllHotReplies")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, HotRepliesProxy>.plusAssign(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.Post>) {
      addAll(values)
    }
    /**
     * ```
     * Hot replies only exist in the main floor.
     * ```
     *
     * `repeated .Post hot_replies = 8;`
     * @param index The index to set the value at.
     * @param value The hotReplies to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setHotReplies")
    public operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, HotRepliesProxy>.set(index: kotlin.Int, value: com.bugenzhao.mnga.protos.datamodel.Post) {
      _builder.setHotReplies(index, value)
    }
    /**
     * ```
     * Hot replies only exist in the main floor.
     * ```
     *
     * `repeated .Post hot_replies = 8;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearHotReplies")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, HotRepliesProxy>.clear() {
      _builder.clearHotReplies()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CommentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Inline replies.
     * ```
     *
     * `repeated .Post comments = 12;`
     */
     public val comments: com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, CommentsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.commentsList
      )
    /**
     * ```
     * Inline replies.
     * ```
     *
     * `repeated .Post comments = 12;`
     * @param value The comments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addComments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, CommentsProxy>.add(value: com.bugenzhao.mnga.protos.datamodel.Post) {
      _builder.addComments(value)
    }
    /**
     * ```
     * Inline replies.
     * ```
     *
     * `repeated .Post comments = 12;`
     * @param value The comments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignComments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, CommentsProxy>.plusAssign(value: com.bugenzhao.mnga.protos.datamodel.Post) {
      add(value)
    }
    /**
     * ```
     * Inline replies.
     * ```
     *
     * `repeated .Post comments = 12;`
     * @param values The comments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllComments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, CommentsProxy>.addAll(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.Post>) {
      _builder.addAllComments(values)
    }
    /**
     * ```
     * Inline replies.
     * ```
     *
     * `repeated .Post comments = 12;`
     * @param values The comments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllComments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, CommentsProxy>.plusAssign(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.Post>) {
      addAll(values)
    }
    /**
     * ```
     * Inline replies.
     * ```
     *
     * `repeated .Post comments = 12;`
     * @param index The index to set the value at.
     * @param value The comments to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setComments")
    public operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, CommentsProxy>.set(index: kotlin.Int, value: com.bugenzhao.mnga.protos.datamodel.Post) {
      _builder.setComments(index, value)
    }
    /**
     * ```
     * Inline replies.
     * ```
     *
     * `repeated .Post comments = 12;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearComments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Post, CommentsProxy>.clear() {
      _builder.clearComments()
    }

    /**
     * `.Device device = 9;`
     */
    public var device: com.bugenzhao.mnga.protos.datamodel.Device
      @kotlin.jvm.JvmName("getDevice")
        get() = _builder.device
      @kotlin.jvm.JvmName("setDevice")
        set(value) {
        _builder.device = value
      }
    public var deviceValue: kotlin.Int
      @kotlin.jvm.JvmName("getDeviceValue")
        get() = _builder.deviceValue
      @kotlin.jvm.JvmName("setDeviceValue")
        set(value) {
        _builder.deviceValue = value
      }
    /**
     * `.Device device = 9;`
     */
    public fun clearDevice() {
      _builder.clearDevice()
    }

    /**
     * ```
     * This post has been altered if it's not empty.
     * ```
     *
     * `string alter_info = 10;`
     */
    public var alterInfo: kotlin.String
      @kotlin.jvm.JvmName("getAlterInfo")
        get() = _builder.alterInfo
      @kotlin.jvm.JvmName("setAlterInfo")
        set(value) {
        _builder.alterInfo = value
      }
    /**
     * ```
     * This post has been altered if it's not empty.
     * ```
     *
     * `string alter_info = 10;`
     */
    public fun clearAlterInfo() {
      _builder.clearAlterInfo()
    }

    /**
     * ```
     * The page which this post belongs to.
     * ```
     *
     * `uint32 at_page = 11;`
     */
    public var atPage: kotlin.Int
      @kotlin.jvm.JvmName("getAtPage")
        get() = _builder.atPage
      @kotlin.jvm.JvmName("setAtPage")
        set(value) {
        _builder.atPage = value
      }
    /**
     * ```
     * The page which this post belongs to.
     * ```
     *
     * `uint32 at_page = 11;`
     */
    public fun clearAtPage() {
      _builder.clearAtPage()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AttachmentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .Attachment attachments = 13;`
     */
     public val attachments: com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Attachment, AttachmentsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.attachmentsList
      )
    /**
     * `repeated .Attachment attachments = 13;`
     * @param value The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Attachment, AttachmentsProxy>.add(value: com.bugenzhao.mnga.protos.datamodel.Attachment) {
      _builder.addAttachments(value)
    }
    /**
     * `repeated .Attachment attachments = 13;`
     * @param value The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAttachments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Attachment, AttachmentsProxy>.plusAssign(value: com.bugenzhao.mnga.protos.datamodel.Attachment) {
      add(value)
    }
    /**
     * `repeated .Attachment attachments = 13;`
     * @param values The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Attachment, AttachmentsProxy>.addAll(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.Attachment>) {
      _builder.addAllAttachments(values)
    }
    /**
     * `repeated .Attachment attachments = 13;`
     * @param values The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAttachments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Attachment, AttachmentsProxy>.plusAssign(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.Attachment>) {
      addAll(values)
    }
    /**
     * `repeated .Attachment attachments = 13;`
     * @param index The index to set the value at.
     * @param value The attachments to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAttachments")
    public operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Attachment, AttachmentsProxy>.set(index: kotlin.Int, value: com.bugenzhao.mnga.protos.datamodel.Attachment) {
      _builder.setAttachments(index, value)
    }
    /**
     * `repeated .Attachment attachments = 13;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Attachment, AttachmentsProxy>.clear() {
      _builder.clearAttachments()
    }

    /**
     * ```
     * The id of the post's parent forum, mainly used for
     * ```
     *
     * `string fid = 14;`
     */
    public var fid: kotlin.String
      @kotlin.jvm.JvmName("getFid")
        get() = _builder.fid
      @kotlin.jvm.JvmName("setFid")
        set(value) {
        _builder.fid = value
      }
    /**
     * ```
     * The id of the post's parent forum, mainly used for
     * ```
     *
     * `string fid = 14;`
     */
    public fun clearFid() {
      _builder.clearFid()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.Post.copy(block: `com.bugenzhao.mnga.protos.datamodel`.PostKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Post =
  `com.bugenzhao.mnga.protos.datamodel`.PostKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.datamodel.PostOrBuilder.idOrNull: com.bugenzhao.mnga.protos.datamodel.PostId?
  get() = if (hasId()) getId() else null

public val com.bugenzhao.mnga.protos.datamodel.PostOrBuilder.contentOrNull: com.bugenzhao.mnga.protos.datamodel.PostContent?
  get() = if (hasContent()) getContent() else null

