// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface PostAttachmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostAttachment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string url = 2;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 2;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * Verification code for posting this attachment.
   * </pre>
   *
   * <code>string check = 3;</code>
   * @return The check.
   */
  java.lang.String getCheck();
  /**
   * <pre>
   * Verification code for posting this attachment.
   * </pre>
   *
   * <code>string check = 3;</code>
   * @return The bytes for check.
   */
  com.google.protobuf.ByteString
      getCheckBytes();
}
