// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

/**
 * <pre>
 * Rich content parsed from bbcode.
 * </pre>
 *
 * Protobuf type {@code PostContent}
 */
@com.google.protobuf.Generated
public final class PostContent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:PostContent)
    PostContentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "PostContent");
  }
  // Use PostContent.newBuilder() to construct.
  private PostContent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PostContent() {
    spans_ = java.util.Collections.emptyList();
    raw_ = "";
    error_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_PostContent_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_PostContent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_PostContent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bugenzhao.mnga.protos.datamodel.PostContent.class, com.bugenzhao.mnga.protos.datamodel.PostContent.Builder.class);
  }

  public static final int SPANS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.bugenzhao.mnga.protos.datamodel.Span> spans_;
  /**
   * <code>repeated .Span spans = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.bugenzhao.mnga.protos.datamodel.Span> getSpansList() {
    return spans_;
  }
  /**
   * <code>repeated .Span spans = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder> 
      getSpansOrBuilderList() {
    return spans_;
  }
  /**
   * <code>repeated .Span spans = 1;</code>
   */
  @java.lang.Override
  public int getSpansCount() {
    return spans_.size();
  }
  /**
   * <code>repeated .Span spans = 1;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.Span getSpans(int index) {
    return spans_.get(index);
  }
  /**
   * <code>repeated .Span spans = 1;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder getSpansOrBuilder(
      int index) {
    return spans_.get(index);
  }

  public static final int RAW_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object raw_ = "";
  /**
   * <pre>
   * Raw bbcode representation of this content.
   * </pre>
   *
   * <code>string raw = 2;</code>
   * @return The raw.
   */
  @java.lang.Override
  public java.lang.String getRaw() {
    java.lang.Object ref = raw_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      raw_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Raw bbcode representation of this content.
   * </pre>
   *
   * <code>string raw = 2;</code>
   * @return The bytes for raw.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRawBytes() {
    java.lang.Object ref = raw_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      raw_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <pre>
   * Parse error.
   * </pre>
   *
   * <code>string error = 3;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Parse error.
   * </pre>
   *
   * <code>string error = 3;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < spans_.size(); i++) {
      output.writeMessage(1, spans_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(raw_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, raw_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, error_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = spans_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(spans_.get(i));
          }
          size += 1 * count;
        }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(raw_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, raw_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, error_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bugenzhao.mnga.protos.datamodel.PostContent)) {
      return super.equals(obj);
    }
    com.bugenzhao.mnga.protos.datamodel.PostContent other = (com.bugenzhao.mnga.protos.datamodel.PostContent) obj;

    if (!getSpansList()
        .equals(other.getSpansList())) return false;
    if (!getRaw()
        .equals(other.getRaw())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSpansCount() > 0) {
      hash = (37 * hash) + SPANS_FIELD_NUMBER;
      hash = (53 * hash) + getSpansList().hashCode();
    }
    hash = (37 * hash) + RAW_FIELD_NUMBER;
    hash = (53 * hash) + getRaw().hashCode();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.datamodel.PostContent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bugenzhao.mnga.protos.datamodel.PostContent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Rich content parsed from bbcode.
   * </pre>
   *
   * Protobuf type {@code PostContent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PostContent)
      com.bugenzhao.mnga.protos.datamodel.PostContentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_PostContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_PostContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bugenzhao.mnga.protos.datamodel.PostContent.class, com.bugenzhao.mnga.protos.datamodel.PostContent.Builder.class);
    }

    // Construct using com.bugenzhao.mnga.protos.datamodel.PostContent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
      } else {
        spans_ = null;
        spansBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      raw_ = "";
      error_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_PostContent_descriptor;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.PostContent getDefaultInstanceForType() {
      return com.bugenzhao.mnga.protos.datamodel.PostContent.getDefaultInstance();
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.PostContent build() {
      com.bugenzhao.mnga.protos.datamodel.PostContent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.PostContent buildPartial() {
      com.bugenzhao.mnga.protos.datamodel.PostContent result = new com.bugenzhao.mnga.protos.datamodel.PostContent(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.bugenzhao.mnga.protos.datamodel.PostContent result) {
      if (spansBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          spans_ = java.util.Collections.unmodifiableList(spans_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.spans_ = spans_;
      } else {
        result.spans_ = spansBuilder_.build();
      }
    }

    private void buildPartial0(com.bugenzhao.mnga.protos.datamodel.PostContent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.raw_ = raw_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = error_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bugenzhao.mnga.protos.datamodel.PostContent) {
        return mergeFrom((com.bugenzhao.mnga.protos.datamodel.PostContent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bugenzhao.mnga.protos.datamodel.PostContent other) {
      if (other == com.bugenzhao.mnga.protos.datamodel.PostContent.getDefaultInstance()) return this;
      if (spansBuilder_ == null) {
        if (!other.spans_.isEmpty()) {
          if (spans_.isEmpty()) {
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpansIsMutable();
            spans_.addAll(other.spans_);
          }
          onChanged();
        }
      } else {
        if (!other.spans_.isEmpty()) {
          if (spansBuilder_.isEmpty()) {
            spansBuilder_.dispose();
            spansBuilder_ = null;
            spans_ = other.spans_;
            bitField0_ = (bitField0_ & ~0x00000001);
            spansBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSpansFieldBuilder() : null;
          } else {
            spansBuilder_.addAllMessages(other.spans_);
          }
        }
      }
      if (!other.getRaw().isEmpty()) {
        raw_ = other.raw_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.bugenzhao.mnga.protos.datamodel.Span m =
                  input.readMessage(
                      com.bugenzhao.mnga.protos.datamodel.Span.parser(),
                      extensionRegistry);
              if (spansBuilder_ == null) {
                ensureSpansIsMutable();
                spans_.add(m);
              } else {
                spansBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              raw_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bugenzhao.mnga.protos.datamodel.Span> spans_ =
      java.util.Collections.emptyList();
    private void ensureSpansIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        spans_ = new java.util.ArrayList<com.bugenzhao.mnga.protos.datamodel.Span>(spans_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.Span, com.bugenzhao.mnga.protos.datamodel.Span.Builder, com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder> spansBuilder_;

    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public java.util.List<com.bugenzhao.mnga.protos.datamodel.Span> getSpansList() {
      if (spansBuilder_ == null) {
        return java.util.Collections.unmodifiableList(spans_);
      } else {
        return spansBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public int getSpansCount() {
      if (spansBuilder_ == null) {
        return spans_.size();
      } else {
        return spansBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Span getSpans(int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);
      } else {
        return spansBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder setSpans(
        int index, com.bugenzhao.mnga.protos.datamodel.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.set(index, value);
        onChanged();
      } else {
        spansBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder setSpans(
        int index, com.bugenzhao.mnga.protos.datamodel.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.set(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder addSpans(com.bugenzhao.mnga.protos.datamodel.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(value);
        onChanged();
      } else {
        spansBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder addSpans(
        int index, com.bugenzhao.mnga.protos.datamodel.Span value) {
      if (spansBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpansIsMutable();
        spans_.add(index, value);
        onChanged();
      } else {
        spansBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder addSpans(
        com.bugenzhao.mnga.protos.datamodel.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder addSpans(
        int index, com.bugenzhao.mnga.protos.datamodel.Span.Builder builderForValue) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.add(index, builderForValue.build());
        onChanged();
      } else {
        spansBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder addAllSpans(
        java.lang.Iterable<? extends com.bugenzhao.mnga.protos.datamodel.Span> values) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, spans_);
        onChanged();
      } else {
        spansBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder clearSpans() {
      if (spansBuilder_ == null) {
        spans_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        spansBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public Builder removeSpans(int index) {
      if (spansBuilder_ == null) {
        ensureSpansIsMutable();
        spans_.remove(index);
        onChanged();
      } else {
        spansBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Span.Builder getSpansBuilder(
        int index) {
      return internalGetSpansFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder getSpansOrBuilder(
        int index) {
      if (spansBuilder_ == null) {
        return spans_.get(index);  } else {
        return spansBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder> 
         getSpansOrBuilderList() {
      if (spansBuilder_ != null) {
        return spansBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(spans_);
      }
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Span.Builder addSpansBuilder() {
      return internalGetSpansFieldBuilder().addBuilder(
          com.bugenzhao.mnga.protos.datamodel.Span.getDefaultInstance());
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Span.Builder addSpansBuilder(
        int index) {
      return internalGetSpansFieldBuilder().addBuilder(
          index, com.bugenzhao.mnga.protos.datamodel.Span.getDefaultInstance());
    }
    /**
     * <code>repeated .Span spans = 1;</code>
     */
    public java.util.List<com.bugenzhao.mnga.protos.datamodel.Span.Builder> 
         getSpansBuilderList() {
      return internalGetSpansFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.Span, com.bugenzhao.mnga.protos.datamodel.Span.Builder, com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder> 
        internalGetSpansFieldBuilder() {
      if (spansBuilder_ == null) {
        spansBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bugenzhao.mnga.protos.datamodel.Span, com.bugenzhao.mnga.protos.datamodel.Span.Builder, com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder>(
                spans_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        spans_ = null;
      }
      return spansBuilder_;
    }

    private java.lang.Object raw_ = "";
    /**
     * <pre>
     * Raw bbcode representation of this content.
     * </pre>
     *
     * <code>string raw = 2;</code>
     * @return The raw.
     */
    public java.lang.String getRaw() {
      java.lang.Object ref = raw_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        raw_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Raw bbcode representation of this content.
     * </pre>
     *
     * <code>string raw = 2;</code>
     * @return The bytes for raw.
     */
    public com.google.protobuf.ByteString
        getRawBytes() {
      java.lang.Object ref = raw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        raw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Raw bbcode representation of this content.
     * </pre>
     *
     * <code>string raw = 2;</code>
     * @param value The raw to set.
     * @return This builder for chaining.
     */
    public Builder setRaw(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      raw_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Raw bbcode representation of this content.
     * </pre>
     *
     * <code>string raw = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRaw() {
      raw_ = getDefaultInstance().getRaw();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Raw bbcode representation of this content.
     * </pre>
     *
     * <code>string raw = 2;</code>
     * @param value The bytes for raw to set.
     * @return This builder for chaining.
     */
    public Builder setRawBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      raw_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <pre>
     * Parse error.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Parse error.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Parse error.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Parse error.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Parse error.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PostContent)
  }

  // @@protoc_insertion_point(class_scope:PostContent)
  private static final com.bugenzhao.mnga.protos.datamodel.PostContent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bugenzhao.mnga.protos.datamodel.PostContent();
  }

  public static com.bugenzhao.mnga.protos.datamodel.PostContent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PostContent>
      PARSER = new com.google.protobuf.AbstractParser<PostContent>() {
    @java.lang.Override
    public PostContent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PostContent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PostContent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.PostContent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

