// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.datamodel;

@kotlin.jvm.JvmName("-initializeshortMessagePost")
public inline fun shortMessagePost(block: com.bugenzhao.mnga.protos.datamodel.ShortMessagePostKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.ShortMessagePost =
  com.bugenzhao.mnga.protos.datamodel.ShortMessagePostKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.ShortMessagePost.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ShortMessagePost`
 */
public object ShortMessagePostKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.datamodel.ShortMessagePost.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.ShortMessagePost.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.datamodel.ShortMessagePost = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string author_id = 2;`
     */
    public var authorId: kotlin.String
      @kotlin.jvm.JvmName("getAuthorId")
        get() = _builder.authorId
      @kotlin.jvm.JvmName("setAuthorId")
        set(value) {
        _builder.authorId = value
      }
    /**
     * `string author_id = 2;`
     */
    public fun clearAuthorId() {
      _builder.clearAuthorId()
    }

    /**
     * `string subject = 3;`
     */
    public var subject: kotlin.String
      @kotlin.jvm.JvmName("getSubject")
        get() = _builder.subject
      @kotlin.jvm.JvmName("setSubject")
        set(value) {
        _builder.subject = value
      }
    /**
     * `string subject = 3;`
     */
    public fun clearSubject() {
      _builder.clearSubject()
    }

    /**
     * `.PostContent content = 4;`
     */
    public var content: com.bugenzhao.mnga.protos.datamodel.PostContent
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `.PostContent content = 4;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * `.PostContent content = 4;`
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }

    public val ShortMessagePostKt.Dsl.contentOrNull: com.bugenzhao.mnga.protos.datamodel.PostContent?
      get() = _builder.contentOrNull

    /**
     * `uint64 post_date = 5;`
     */
    public var postDate: kotlin.Long
      @kotlin.jvm.JvmName("getPostDate")
        get() = _builder.postDate
      @kotlin.jvm.JvmName("setPostDate")
        set(value) {
        _builder.postDate = value
      }
    /**
     * `uint64 post_date = 5;`
     */
    public fun clearPostDate() {
      _builder.clearPostDate()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.ShortMessagePost.copy(block: `com.bugenzhao.mnga.protos.datamodel`.ShortMessagePostKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.ShortMessagePost =
  `com.bugenzhao.mnga.protos.datamodel`.ShortMessagePostKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.datamodel.ShortMessagePostOrBuilder.contentOrNull: com.bugenzhao.mnga.protos.datamodel.PostContent?
  get() = if (hasContent()) getContent() else null

