// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.datamodel;

@kotlin.jvm.JvmName("-initializeshortMessage")
public inline fun shortMessage(block: com.bugenzhao.mnga.protos.datamodel.ShortMessageKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.ShortMessage =
  com.bugenzhao.mnga.protos.datamodel.ShortMessageKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.ShortMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * Info of one short message conversation, contains a list of posts.
 * ```
 *
 * Protobuf type `ShortMessage`
 */
public object ShortMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.datamodel.ShortMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.ShortMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.datamodel.ShortMessage = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string subject = 2;`
     */
    public var subject: kotlin.String
      @kotlin.jvm.JvmName("getSubject")
        get() = _builder.subject
      @kotlin.jvm.JvmName("setSubject")
        set(value) {
        _builder.subject = value
      }
    /**
     * `string subject = 2;`
     */
    public fun clearSubject() {
      _builder.clearSubject()
    }

    /**
     * `string from_id = 3;`
     */
    public var fromId: kotlin.String
      @kotlin.jvm.JvmName("getFromId")
        get() = _builder.fromId
      @kotlin.jvm.JvmName("setFromId")
        set(value) {
        _builder.fromId = value
      }
    /**
     * `string from_id = 3;`
     */
    public fun clearFromId() {
      _builder.clearFromId()
    }

    /**
     * `string from_name = 4;`
     */
    public var fromName: kotlin.String
      @kotlin.jvm.JvmName("getFromName")
        get() = _builder.fromName
      @kotlin.jvm.JvmName("setFromName")
        set(value) {
        _builder.fromName = value
      }
    /**
     * `string from_name = 4;`
     */
    public fun clearFromName() {
      _builder.clearFromName()
    }

    /**
     * `uint64 post_date = 5;`
     */
    public var postDate: kotlin.Long
      @kotlin.jvm.JvmName("getPostDate")
        get() = _builder.postDate
      @kotlin.jvm.JvmName("setPostDate")
        set(value) {
        _builder.postDate = value
      }
    /**
     * `uint64 post_date = 5;`
     */
    public fun clearPostDate() {
      _builder.clearPostDate()
    }

    /**
     * `uint64 last_post_date = 6;`
     */
    public var lastPostDate: kotlin.Long
      @kotlin.jvm.JvmName("getLastPostDate")
        get() = _builder.lastPostDate
      @kotlin.jvm.JvmName("setLastPostDate")
        set(value) {
        _builder.lastPostDate = value
      }
    /**
     * `uint64 last_post_date = 6;`
     */
    public fun clearLastPostDate() {
      _builder.clearLastPostDate()
    }

    /**
     * `uint32 post_num = 7;`
     */
    public var postNum: kotlin.Int
      @kotlin.jvm.JvmName("getPostNum")
        get() = _builder.postNum
      @kotlin.jvm.JvmName("setPostNum")
        set(value) {
        _builder.postNum = value
      }
    /**
     * `uint32 post_num = 7;`
     */
    public fun clearPostNum() {
      _builder.clearPostNum()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class IdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string ids = 8;`
     * @return A list containing the ids.
     */
    public val ids: com.google.protobuf.kotlin.DslList<kotlin.String, IdsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.idsList
      )
    /**
     * `repeated string ids = 8;`
     * @param value The ids to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, IdsProxy>.add(value: kotlin.String) {
      _builder.addIds(value)
    }
    /**
     * `repeated string ids = 8;`
     * @param value The ids to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IdsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string ids = 8;`
     * @param values The ids to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, IdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllIds(values)
    }
    /**
     * `repeated string ids = 8;`
     * @param values The ids to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string ids = 8;`
     * @param index The index to set the value at.
     * @param value The ids to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, IdsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setIds(index, value)
    }/**
     * `repeated string ids = 8;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, IdsProxy>.clear() {
      _builder.clearIds()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UserNamesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .UserName user_names = 9;`
     */
     public val userNames: com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.UserName, UserNamesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.userNamesList
      )
    /**
     * `repeated .UserName user_names = 9;`
     * @param value The userNames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addUserNames")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.UserName, UserNamesProxy>.add(value: com.bugenzhao.mnga.protos.datamodel.UserName) {
      _builder.addUserNames(value)
    }
    /**
     * `repeated .UserName user_names = 9;`
     * @param value The userNames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignUserNames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.UserName, UserNamesProxy>.plusAssign(value: com.bugenzhao.mnga.protos.datamodel.UserName) {
      add(value)
    }
    /**
     * `repeated .UserName user_names = 9;`
     * @param values The userNames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllUserNames")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.UserName, UserNamesProxy>.addAll(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.UserName>) {
      _builder.addAllUserNames(values)
    }
    /**
     * `repeated .UserName user_names = 9;`
     * @param values The userNames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllUserNames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.UserName, UserNamesProxy>.plusAssign(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.UserName>) {
      addAll(values)
    }
    /**
     * `repeated .UserName user_names = 9;`
     * @param index The index to set the value at.
     * @param value The userNames to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setUserNames")
    public operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.UserName, UserNamesProxy>.set(index: kotlin.Int, value: com.bugenzhao.mnga.protos.datamodel.UserName) {
      _builder.setUserNames(index, value)
    }
    /**
     * `repeated .UserName user_names = 9;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearUserNames")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.UserName, UserNamesProxy>.clear() {
      _builder.clearUserNames()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.ShortMessage.copy(block: `com.bugenzhao.mnga.protos.datamodel`.ShortMessageKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.ShortMessage =
  `com.bugenzhao.mnga.protos.datamodel`.ShortMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

