// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface ShortMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShortMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string subject = 2;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 2;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string from_id = 3;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <code>string from_id = 3;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <code>string from_name = 4;</code>
   * @return The fromName.
   */
  java.lang.String getFromName();
  /**
   * <code>string from_name = 4;</code>
   * @return The bytes for fromName.
   */
  com.google.protobuf.ByteString
      getFromNameBytes();

  /**
   * <code>uint64 post_date = 5;</code>
   * @return The postDate.
   */
  long getPostDate();

  /**
   * <code>uint64 last_post_date = 6;</code>
   * @return The lastPostDate.
   */
  long getLastPostDate();

  /**
   * <code>uint32 post_num = 7;</code>
   * @return The postNum.
   */
  int getPostNum();

  /**
   * <code>repeated string ids = 8;</code>
   * @return A list containing the ids.
   */
  java.util.List<java.lang.String>
      getIdsList();
  /**
   * <code>repeated string ids = 8;</code>
   * @return The count of ids.
   */
  int getIdsCount();
  /**
   * <code>repeated string ids = 8;</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  java.lang.String getIds(int index);
  /**
   * <code>repeated string ids = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the ids at the given index.
   */
  com.google.protobuf.ByteString
      getIdsBytes(int index);

  /**
   * <code>repeated .UserName user_names = 9;</code>
   */
  java.util.List<com.bugenzhao.mnga.protos.datamodel.UserName> 
      getUserNamesList();
  /**
   * <code>repeated .UserName user_names = 9;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.UserName getUserNames(int index);
  /**
   * <code>repeated .UserName user_names = 9;</code>
   */
  int getUserNamesCount();
  /**
   * <code>repeated .UserName user_names = 9;</code>
   */
  java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.UserNameOrBuilder> 
      getUserNamesOrBuilderList();
  /**
   * <code>repeated .UserName user_names = 9;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.UserNameOrBuilder getUserNamesOrBuilder(
      int index);
}
