// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.datamodel;

@kotlin.jvm.JvmName("-initializespan")
public inline fun span(block: com.bugenzhao.mnga.protos.datamodel.SpanKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span =
  com.bugenzhao.mnga.protos.datamodel.SpanKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.Span.newBuilder()).apply { block() }._build()
/**
 * ```
 * Part of rich contents.
 * ```
 *
 * Protobuf type `Span`
 */
public object SpanKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.datamodel.Span.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.Span.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.datamodel.Span = _builder.build()

    /**
     * `.Span.Plain plain = 1;`
     */
    public var plain: com.bugenzhao.mnga.protos.datamodel.Span.Plain
      @kotlin.jvm.JvmName("getPlain")
        get() = _builder.plain
      @kotlin.jvm.JvmName("setPlain")
        set(value) {
        _builder.plain = value
      }
    /**
     * `.Span.Plain plain = 1;`
     */
    public fun clearPlain() {
      _builder.clearPlain()
    }
    /**
     * `.Span.Plain plain = 1;`
     * @return Whether the plain field is set.
     */
    public fun hasPlain(): kotlin.Boolean {
      return _builder.hasPlain()
    }

    /**
     * `.Span.BreakLine break_line = 2;`
     */
    public var breakLine: com.bugenzhao.mnga.protos.datamodel.Span.BreakLine
      @kotlin.jvm.JvmName("getBreakLine")
        get() = _builder.breakLine
      @kotlin.jvm.JvmName("setBreakLine")
        set(value) {
        _builder.breakLine = value
      }
    /**
     * `.Span.BreakLine break_line = 2;`
     */
    public fun clearBreakLine() {
      _builder.clearBreakLine()
    }
    /**
     * `.Span.BreakLine break_line = 2;`
     * @return Whether the breakLine field is set.
     */
    public fun hasBreakLine(): kotlin.Boolean {
      return _builder.hasBreakLine()
    }

    /**
     * `.Span.Sticker sticker = 3;`
     */
    public var sticker: com.bugenzhao.mnga.protos.datamodel.Span.Sticker
      @kotlin.jvm.JvmName("getSticker")
        get() = _builder.sticker
      @kotlin.jvm.JvmName("setSticker")
        set(value) {
        _builder.sticker = value
      }
    /**
     * `.Span.Sticker sticker = 3;`
     */
    public fun clearSticker() {
      _builder.clearSticker()
    }
    /**
     * `.Span.Sticker sticker = 3;`
     * @return Whether the sticker field is set.
     */
    public fun hasSticker(): kotlin.Boolean {
      return _builder.hasSticker()
    }

    /**
     * `.Span.Tagged tagged = 4;`
     */
    public var tagged: com.bugenzhao.mnga.protos.datamodel.Span.Tagged
      @kotlin.jvm.JvmName("getTagged")
        get() = _builder.tagged
      @kotlin.jvm.JvmName("setTagged")
        set(value) {
        _builder.tagged = value
      }
    /**
     * `.Span.Tagged tagged = 4;`
     */
    public fun clearTagged() {
      _builder.clearTagged()
    }
    /**
     * `.Span.Tagged tagged = 4;`
     * @return Whether the tagged field is set.
     */
    public fun hasTagged(): kotlin.Boolean {
      return _builder.hasTagged()
    }
    public val valueCase: com.bugenzhao.mnga.protos.datamodel.Span.ValueCase
    @kotlin.jvm.JvmName("getValueCase")
      get() = _builder.getValueCase()

    public fun clearValue() {
      _builder.clearValue()
    }
  }
  @kotlin.jvm.JvmName("-initializeplain")
  public inline fun plain(block: com.bugenzhao.mnga.protos.datamodel.SpanKt.PlainKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span.Plain =
    com.bugenzhao.mnga.protos.datamodel.SpanKt.PlainKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.Span.Plain.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Span.Plain`
   */
  public object PlainKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.bugenzhao.mnga.protos.datamodel.Span.Plain.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.Span.Plain.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): com.bugenzhao.mnga.protos.datamodel.Span.Plain = _builder.build()

      /**
       * `string text = 1;`
       */
      public var text: kotlin.String
        @kotlin.jvm.JvmName("getText")
          get() = _builder.text
        @kotlin.jvm.JvmName("setText")
          set(value) {
          _builder.text = value
        }
      /**
       * `string text = 1;`
       */
      public fun clearText() {
        _builder.clearText()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializebreakLine")
  public inline fun breakLine(block: com.bugenzhao.mnga.protos.datamodel.SpanKt.BreakLineKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span.BreakLine =
    com.bugenzhao.mnga.protos.datamodel.SpanKt.BreakLineKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.Span.BreakLine.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Span.BreakLine`
   */
  public object BreakLineKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.bugenzhao.mnga.protos.datamodel.Span.BreakLine.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.Span.BreakLine.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): com.bugenzhao.mnga.protos.datamodel.Span.BreakLine = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializesticker")
  public inline fun sticker(block: com.bugenzhao.mnga.protos.datamodel.SpanKt.StickerKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span.Sticker =
    com.bugenzhao.mnga.protos.datamodel.SpanKt.StickerKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.Span.Sticker.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Span.Sticker`
   */
  public object StickerKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.bugenzhao.mnga.protos.datamodel.Span.Sticker.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.Span.Sticker.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): com.bugenzhao.mnga.protos.datamodel.Span.Sticker = _builder.build()

      /**
       * `string name = 1;`
       */
      public var name: kotlin.String
        @kotlin.jvm.JvmName("getName")
          get() = _builder.name
        @kotlin.jvm.JvmName("setName")
          set(value) {
          _builder.name = value
        }
      /**
       * `string name = 1;`
       */
      public fun clearName() {
        _builder.clearName()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializetagged")
  public inline fun tagged(block: com.bugenzhao.mnga.protos.datamodel.SpanKt.TaggedKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span.Tagged =
    com.bugenzhao.mnga.protos.datamodel.SpanKt.TaggedKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.Span.Tagged.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Span.Tagged`
   */
  public object TaggedKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.bugenzhao.mnga.protos.datamodel.Span.Tagged.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.Span.Tagged.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): com.bugenzhao.mnga.protos.datamodel.Span.Tagged = _builder.build()

      /**
       * `string tag = 1;`
       */
      public var tag: kotlin.String
        @kotlin.jvm.JvmName("getTag")
          get() = _builder.tag
        @kotlin.jvm.JvmName("setTag")
          set(value) {
          _builder.tag = value
        }
      /**
       * `string tag = 1;`
       */
      public fun clearTag() {
        _builder.clearTag()
      }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class AttributesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated string attributes = 2;`
       * @return A list containing the attributes.
       */
      public val attributes: com.google.protobuf.kotlin.DslList<kotlin.String, AttributesProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        get() = com.google.protobuf.kotlin.DslList(
          _builder.attributesList
        )
      /**
       * `repeated string attributes = 2;`
       * @param value The attributes to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAttributes")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttributesProxy>.add(value: kotlin.String) {
        _builder.addAttributes(value)
      }
      /**
       * `repeated string attributes = 2;`
       * @param value The attributes to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAttributes")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttributesProxy>.plusAssign(value: kotlin.String) {
        add(value)
      }
      /**
       * `repeated string attributes = 2;`
       * @param values The attributes to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAttributes")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttributesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
        _builder.addAllAttributes(values)
      }
      /**
       * `repeated string attributes = 2;`
       * @param values The attributes to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAttributes")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttributesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
        addAll(values)
      }
      /**
       * `repeated string attributes = 2;`
       * @param index The index to set the value at.
       * @param value The attributes to set.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAttributes")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, AttributesProxy>.set(index: kotlin.Int, value: kotlin.String) {
        _builder.setAttributes(index, value)
      }/**
       * `repeated string attributes = 2;`
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAttributes")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, AttributesProxy>.clear() {
        _builder.clearAttributes()
      }
      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class ComplexAttributesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated string complex_attributes = 4;`
       * @return A list containing the complexAttributes.
       */
      public val complexAttributes: com.google.protobuf.kotlin.DslList<kotlin.String, ComplexAttributesProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
        get() = com.google.protobuf.kotlin.DslList(
          _builder.complexAttributesList
        )
      /**
       * `repeated string complex_attributes = 4;`
       * @param value The complexAttributes to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addComplexAttributes")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, ComplexAttributesProxy>.add(value: kotlin.String) {
        _builder.addComplexAttributes(value)
      }
      /**
       * `repeated string complex_attributes = 4;`
       * @param value The complexAttributes to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignComplexAttributes")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ComplexAttributesProxy>.plusAssign(value: kotlin.String) {
        add(value)
      }
      /**
       * `repeated string complex_attributes = 4;`
       * @param values The complexAttributes to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllComplexAttributes")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, ComplexAttributesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
        _builder.addAllComplexAttributes(values)
      }
      /**
       * `repeated string complex_attributes = 4;`
       * @param values The complexAttributes to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllComplexAttributes")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ComplexAttributesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
        addAll(values)
      }
      /**
       * `repeated string complex_attributes = 4;`
       * @param index The index to set the value at.
       * @param value The complexAttributes to set.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setComplexAttributes")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ComplexAttributesProxy>.set(index: kotlin.Int, value: kotlin.String) {
        _builder.setComplexAttributes(index, value)
      }/**
       * `repeated string complex_attributes = 4;`
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setComplexAttributes")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, ComplexAttributesProxy>.clear() {
        _builder.clearComplexAttributes()
      }
      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class SpansProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * Children span nodes.
       * ```
       *
       * `repeated .Span spans = 3;`
       */
       public val spans: com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Span, SpansProxy>
        @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
          _builder.spansList
        )
      /**
       * ```
       * Children span nodes.
       * ```
       *
       * `repeated .Span spans = 3;`
       * @param value The spans to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSpans")
      public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Span, SpansProxy>.add(value: com.bugenzhao.mnga.protos.datamodel.Span) {
        _builder.addSpans(value)
      }
      /**
       * ```
       * Children span nodes.
       * ```
       *
       * `repeated .Span spans = 3;`
       * @param value The spans to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSpans")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Span, SpansProxy>.plusAssign(value: com.bugenzhao.mnga.protos.datamodel.Span) {
        add(value)
      }
      /**
       * ```
       * Children span nodes.
       * ```
       *
       * `repeated .Span spans = 3;`
       * @param values The spans to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSpans")
      public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Span, SpansProxy>.addAll(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.Span>) {
        _builder.addAllSpans(values)
      }
      /**
       * ```
       * Children span nodes.
       * ```
       *
       * `repeated .Span spans = 3;`
       * @param values The spans to add.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSpans")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Span, SpansProxy>.plusAssign(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.Span>) {
        addAll(values)
      }
      /**
       * ```
       * Children span nodes.
       * ```
       *
       * `repeated .Span spans = 3;`
       * @param index The index to set the value at.
       * @param value The spans to set.
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSpans")
      public operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Span, SpansProxy>.set(index: kotlin.Int, value: com.bugenzhao.mnga.protos.datamodel.Span) {
        _builder.setSpans(index, value)
      }
      /**
       * ```
       * Children span nodes.
       * ```
       *
       * `repeated .Span spans = 3;`
       */
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSpans")
      public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.Span, SpansProxy>.clear() {
        _builder.clearSpans()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.Span.copy(block: `com.bugenzhao.mnga.protos.datamodel`.SpanKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span =
  `com.bugenzhao.mnga.protos.datamodel`.SpanKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.Span.Plain.copy(block: `com.bugenzhao.mnga.protos.datamodel`.SpanKt.PlainKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span.Plain =
  `com.bugenzhao.mnga.protos.datamodel`.SpanKt.PlainKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.Span.BreakLine.copy(block: `com.bugenzhao.mnga.protos.datamodel`.SpanKt.BreakLineKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span.BreakLine =
  `com.bugenzhao.mnga.protos.datamodel`.SpanKt.BreakLineKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.Span.Sticker.copy(block: `com.bugenzhao.mnga.protos.datamodel`.SpanKt.StickerKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span.Sticker =
  `com.bugenzhao.mnga.protos.datamodel`.SpanKt.StickerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.Span.Tagged.copy(block: `com.bugenzhao.mnga.protos.datamodel`.SpanKt.TaggedKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Span.Tagged =
  `com.bugenzhao.mnga.protos.datamodel`.SpanKt.TaggedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder.plainOrNull: com.bugenzhao.mnga.protos.datamodel.Span.Plain?
  get() = if (hasPlain()) getPlain() else null

public val com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder.breakLineOrNull: com.bugenzhao.mnga.protos.datamodel.Span.BreakLine?
  get() = if (hasBreakLine()) getBreakLine() else null

public val com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder.stickerOrNull: com.bugenzhao.mnga.protos.datamodel.Span.Sticker?
  get() = if (hasSticker()) getSticker() else null

public val com.bugenzhao.mnga.protos.datamodel.SpanOrBuilder.taggedOrNull: com.bugenzhao.mnga.protos.datamodel.Span.Tagged?
  get() = if (hasTagged()) getTagged() else null

