// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.datamodel;

@kotlin.jvm.JvmName("-initializesubforum")
public inline fun subforum(block: com.bugenzhao.mnga.protos.datamodel.SubforumKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Subforum =
  com.bugenzhao.mnga.protos.datamodel.SubforumKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.Subforum.newBuilder()).apply { block() }._build()
/**
 * ```
 * Children of a parent forum, can be subscribed or unsubscribed.
 * ```
 *
 * Protobuf type `Subforum`
 */
public object SubforumKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.datamodel.Subforum.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.Subforum.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.datamodel.Subforum = _builder.build()

    /**
     * ```
     * Info of the subforum.
     * ```
     *
     * `.Forum forum = 8;`
     */
    public var forum: com.bugenzhao.mnga.protos.datamodel.Forum
      @kotlin.jvm.JvmName("getForum")
        get() = _builder.forum
      @kotlin.jvm.JvmName("setForum")
        set(value) {
        _builder.forum = value
      }
    /**
     * ```
     * Info of the subforum.
     * ```
     *
     * `.Forum forum = 8;`
     */
    public fun clearForum() {
      _builder.clearForum()
    }
    /**
     * ```
     * Info of the subforum.
     * ```
     *
     * `.Forum forum = 8;`
     * @return Whether the forum field is set.
     */
    public fun hasForum(): kotlin.Boolean {
      return _builder.hasForum()
    }

    public val SubforumKt.Dsl.forumOrNull: com.bugenzhao.mnga.protos.datamodel.Forum?
      get() = _builder.forumOrNull

    /**
     * ```
     * ID used for sending request to (un)subcribe self.
     * ```
     *
     * `string filter_id = 7;`
     */
    public var filterId: kotlin.String
      @kotlin.jvm.JvmName("getFilterId")
        get() = _builder.filterId
      @kotlin.jvm.JvmName("setFilterId")
        set(value) {
        _builder.filterId = value
      }
    /**
     * ```
     * ID used for sending request to (un)subcribe self.
     * ```
     *
     * `string filter_id = 7;`
     */
    public fun clearFilterId() {
      _builder.clearFilterId()
    }

    /**
     * `uint64 attributes = 4;`
     */
    public var attributes: kotlin.Long
      @kotlin.jvm.JvmName("getAttributes")
        get() = _builder.attributes
      @kotlin.jvm.JvmName("setAttributes")
        set(value) {
        _builder.attributes = value
      }
    /**
     * `uint64 attributes = 4;`
     */
    public fun clearAttributes() {
      _builder.clearAttributes()
    }

    /**
     * ```
     * Whether this subforum is able to be unsubscribed.
     * ```
     *
     * `bool filterable = 5;`
     */
    public var filterable: kotlin.Boolean
      @kotlin.jvm.JvmName("getFilterable")
        get() = _builder.filterable
      @kotlin.jvm.JvmName("setFilterable")
        set(value) {
        _builder.filterable = value
      }
    /**
     * ```
     * Whether this subforum is able to be unsubscribed.
     * ```
     *
     * `bool filterable = 5;`
     */
    public fun clearFilterable() {
      _builder.clearFilterable()
    }

    /**
     * ```
     * Whether this subforum is subscribed in its parent forum.
     * ```
     *
     * `bool selected = 6;`
     */
    public var selected: kotlin.Boolean
      @kotlin.jvm.JvmName("getSelected")
        get() = _builder.selected
      @kotlin.jvm.JvmName("setSelected")
        set(value) {
        _builder.selected = value
      }
    /**
     * ```
     * Whether this subforum is subscribed in its parent forum.
     * ```
     *
     * `bool selected = 6;`
     */
    public fun clearSelected() {
      _builder.clearSelected()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.Subforum.copy(block: `com.bugenzhao.mnga.protos.datamodel`.SubforumKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.Subforum =
  `com.bugenzhao.mnga.protos.datamodel`.SubforumKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.datamodel.SubforumOrBuilder.forumOrNull: com.bugenzhao.mnga.protos.datamodel.Forum?
  get() = if (hasForum()) getForum() else null

