// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.datamodel;

@kotlin.jvm.JvmName("-initializetopicWithLightPost")
public inline fun topicWithLightPost(block: com.bugenzhao.mnga.protos.datamodel.TopicWithLightPostKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.TopicWithLightPost =
  com.bugenzhao.mnga.protos.datamodel.TopicWithLightPostKt.Dsl._create(com.bugenzhao.mnga.protos.datamodel.TopicWithLightPost.newBuilder()).apply { block() }._build()
/**
 * ```
 * Combination of `Topic` and `LightPost`, used for posts of some user.
 * ```
 *
 * Protobuf type `TopicWithLightPost`
 */
public object TopicWithLightPostKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.datamodel.TopicWithLightPost.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.datamodel.TopicWithLightPost.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.datamodel.TopicWithLightPost = _builder.build()

    /**
     * `.Topic topic = 1;`
     */
    public var topic: com.bugenzhao.mnga.protos.datamodel.Topic
      @kotlin.jvm.JvmName("getTopic")
        get() = _builder.topic
      @kotlin.jvm.JvmName("setTopic")
        set(value) {
        _builder.topic = value
      }
    /**
     * `.Topic topic = 1;`
     */
    public fun clearTopic() {
      _builder.clearTopic()
    }
    /**
     * `.Topic topic = 1;`
     * @return Whether the topic field is set.
     */
    public fun hasTopic(): kotlin.Boolean {
      return _builder.hasTopic()
    }

    public val TopicWithLightPostKt.Dsl.topicOrNull: com.bugenzhao.mnga.protos.datamodel.Topic?
      get() = _builder.topicOrNull

    /**
     * `.LightPost post = 2;`
     */
    public var post: com.bugenzhao.mnga.protos.datamodel.LightPost
      @kotlin.jvm.JvmName("getPost")
        get() = _builder.post
      @kotlin.jvm.JvmName("setPost")
        set(value) {
        _builder.post = value
      }
    /**
     * `.LightPost post = 2;`
     */
    public fun clearPost() {
      _builder.clearPost()
    }
    /**
     * `.LightPost post = 2;`
     * @return Whether the post field is set.
     */
    public fun hasPost(): kotlin.Boolean {
      return _builder.hasPost()
    }

    public val TopicWithLightPostKt.Dsl.postOrNull: com.bugenzhao.mnga.protos.datamodel.LightPost?
      get() = _builder.postOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.datamodel.TopicWithLightPost.copy(block: `com.bugenzhao.mnga.protos.datamodel`.TopicWithLightPostKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.datamodel.TopicWithLightPost =
  `com.bugenzhao.mnga.protos.datamodel`.TopicWithLightPostKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.datamodel.TopicWithLightPostOrBuilder.topicOrNull: com.bugenzhao.mnga.protos.datamodel.Topic?
  get() = if (hasTopic()) getTopic() else null

public val com.bugenzhao.mnga.protos.datamodel.TopicWithLightPostOrBuilder.postOrNull: com.bugenzhao.mnga.protos.datamodel.LightPost?
  get() = if (hasPost()) getPost() else null

