// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

@com.google.protobuf.Generated
public interface UserNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Original name of a user, will always be some.
   * </pre>
   *
   * <code>string normal = 1;</code>
   * @return The normal.
   */
  java.lang.String getNormal();
  /**
   * <pre>
   * Original name of a user, will always be some.
   * </pre>
   *
   * <code>string normal = 1;</code>
   * @return The bytes for normal.
   */
  com.google.protobuf.ByteString
      getNormalBytes();

  /**
   * <pre>
   * Anonymous representation of a user name, if exists.
   * </pre>
   *
   * <code>string anonymous = 2;</code>
   * @return The anonymous.
   */
  java.lang.String getAnonymous();
  /**
   * <pre>
   * Anonymous representation of a user name, if exists.
   * </pre>
   *
   * <code>string anonymous = 2;</code>
   * @return The bytes for anonymous.
   */
  com.google.protobuf.ByteString
      getAnonymousBytes();
}
