// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DataModel.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.datamodel;

/**
 * Protobuf type {@code User}
 */
@com.google.protobuf.Generated
public final class User extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "User");
  }
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private User() {
    id_ = "";
    avatarUrl_ = "";
    nameRaw_ = "";
    ipLocation_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_User_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bugenzhao.mnga.protos.datamodel.User.class, com.bugenzhao.mnga.protos.datamodel.User.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 8;
  private com.bugenzhao.mnga.protos.datamodel.UserName name_;
  /**
   * <code>.UserName name = 8;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.UserName name = 8;</code>
   * @return The name.
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.UserName getName() {
    return name_ == null ? com.bugenzhao.mnga.protos.datamodel.UserName.getDefaultInstance() : name_;
  }
  /**
   * <code>.UserName name = 8;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.UserNameOrBuilder getNameOrBuilder() {
    return name_ == null ? com.bugenzhao.mnga.protos.datamodel.UserName.getDefaultInstance() : name_;
  }

  public static final int AVATAR_URL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object avatarUrl_ = "";
  /**
   * <code>string avatar_url = 3;</code>
   * @return The avatarUrl.
   */
  @java.lang.Override
  public java.lang.String getAvatarUrl() {
    java.lang.Object ref = avatarUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatarUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string avatar_url = 3;</code>
   * @return The bytes for avatarUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAvatarUrlBytes() {
    java.lang.Object ref = avatarUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatarUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REG_DATE_FIELD_NUMBER = 4;
  private long regDate_ = 0L;
  /**
   * <pre>
   * The timestamp of the user's registration.
   * </pre>
   *
   * <code>uint64 reg_date = 4;</code>
   * @return The regDate.
   */
  @java.lang.Override
  public long getRegDate() {
    return regDate_;
  }

  public static final int POST_NUM_FIELD_NUMBER = 5;
  private int postNum_ = 0;
  /**
   * <code>uint32 post_num = 5;</code>
   * @return The postNum.
   */
  @java.lang.Override
  public int getPostNum() {
    return postNum_;
  }

  public static final int FAME_FIELD_NUMBER = 6;
  private long fame_ = 0L;
  /**
   * <pre>
   * Should be resolved as `fame / 10`.
   * </pre>
   *
   * <code>sint64 fame = 6;</code>
   * @return The fame.
   */
  @java.lang.Override
  public long getFame() {
    return fame_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 7;
  private com.bugenzhao.mnga.protos.datamodel.PostContent signature_;
  /**
   * <code>.PostContent signature = 7;</code>
   * @return Whether the signature field is set.
   */
  @java.lang.Override
  public boolean hasSignature() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.PostContent signature = 7;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.PostContent getSignature() {
    return signature_ == null ? com.bugenzhao.mnga.protos.datamodel.PostContent.getDefaultInstance() : signature_;
  }
  /**
   * <code>.PostContent signature = 7;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.PostContentOrBuilder getSignatureOrBuilder() {
    return signature_ == null ? com.bugenzhao.mnga.protos.datamodel.PostContent.getDefaultInstance() : signature_;
  }

  public static final int NAME_RAW_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nameRaw_ = "";
  /**
   * <code>string name_raw = 2 [deprecated = true];</code>
   * @deprecated User.name_raw is deprecated.
   *     See DataModel.proto;l=62
   * @return The nameRaw.
   */
  @java.lang.Override
  @java.lang.Deprecated public java.lang.String getNameRaw() {
    java.lang.Object ref = nameRaw_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameRaw_ = s;
      return s;
    }
  }
  /**
   * <code>string name_raw = 2 [deprecated = true];</code>
   * @deprecated User.name_raw is deprecated.
   *     See DataModel.proto;l=62
   * @return The bytes for nameRaw.
   */
  @java.lang.Override
  @java.lang.Deprecated public com.google.protobuf.ByteString
      getNameRawBytes() {
    java.lang.Object ref = nameRaw_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameRaw_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MUTE_FIELD_NUMBER = 9;
  private boolean mute_ = false;
  /**
   * <pre>
   * Whether the user is temporarily banned by NGA.
   * </pre>
   *
   * <code>bool mute = 9;</code>
   * @return The mute.
   */
  @java.lang.Override
  public boolean getMute() {
    return mute_;
  }

  public static final int IP_LOCATION_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ipLocation_ = "";
  /**
   * <code>string ip_location = 10;</code>
   * @return The ipLocation.
   */
  @java.lang.Override
  public java.lang.String getIpLocation() {
    java.lang.Object ref = ipLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string ip_location = 10;</code>
   * @return The bytes for ipLocation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIpLocationBytes() {
    java.lang.Object ref = ipLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REMOTE_FIELD_NUMBER = 11;
  private boolean remote_ = false;
  /**
   * <pre>
   * Whether this user info is fetched with a separate `remoteUser` call.
   * </pre>
   *
   * <code>bool remote = 11;</code>
   * @return The remote.
   */
  @java.lang.Override
  public boolean getRemote() {
    return remote_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameRaw_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, nameRaw_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(avatarUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, avatarUrl_);
    }
    if (regDate_ != 0L) {
      output.writeUInt64(4, regDate_);
    }
    if (postNum_ != 0) {
      output.writeUInt32(5, postNum_);
    }
    if (fame_ != 0L) {
      output.writeSInt64(6, fame_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(7, getSignature());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(8, getName());
    }
    if (mute_ != false) {
      output.writeBool(9, mute_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ipLocation_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, ipLocation_);
    }
    if (remote_ != false) {
      output.writeBool(11, remote_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nameRaw_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nameRaw_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(avatarUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, avatarUrl_);
    }
    if (regDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, regDate_);
    }
    if (postNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, postNum_);
    }
    if (fame_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(6, fame_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getSignature());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getName());
    }
    if (mute_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, mute_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ipLocation_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, ipLocation_);
    }
    if (remote_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, remote_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bugenzhao.mnga.protos.datamodel.User)) {
      return super.equals(obj);
    }
    com.bugenzhao.mnga.protos.datamodel.User other = (com.bugenzhao.mnga.protos.datamodel.User) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (!getAvatarUrl()
        .equals(other.getAvatarUrl())) return false;
    if (getRegDate()
        != other.getRegDate()) return false;
    if (getPostNum()
        != other.getPostNum()) return false;
    if (getFame()
        != other.getFame()) return false;
    if (hasSignature() != other.hasSignature()) return false;
    if (hasSignature()) {
      if (!getSignature()
          .equals(other.getSignature())) return false;
    }
    if (!getNameRaw()
        .equals(other.getNameRaw())) return false;
    if (getMute()
        != other.getMute()) return false;
    if (!getIpLocation()
        .equals(other.getIpLocation())) return false;
    if (getRemote()
        != other.getRemote()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    hash = (37 * hash) + AVATAR_URL_FIELD_NUMBER;
    hash = (53 * hash) + getAvatarUrl().hashCode();
    hash = (37 * hash) + REG_DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRegDate());
    hash = (37 * hash) + POST_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getPostNum();
    hash = (37 * hash) + FAME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFame());
    if (hasSignature()) {
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
    }
    hash = (37 * hash) + NAME_RAW_FIELD_NUMBER;
    hash = (53 * hash) + getNameRaw().hashCode();
    hash = (37 * hash) + MUTE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMute());
    hash = (37 * hash) + IP_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getIpLocation().hashCode();
    hash = (37 * hash) + REMOTE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRemote());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bugenzhao.mnga.protos.datamodel.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bugenzhao.mnga.protos.datamodel.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.datamodel.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bugenzhao.mnga.protos.datamodel.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:User)
      com.bugenzhao.mnga.protos.datamodel.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bugenzhao.mnga.protos.datamodel.User.class, com.bugenzhao.mnga.protos.datamodel.User.Builder.class);
    }

    // Construct using com.bugenzhao.mnga.protos.datamodel.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetNameFieldBuilder();
        internalGetSignatureFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = null;
      if (nameBuilder_ != null) {
        nameBuilder_.dispose();
        nameBuilder_ = null;
      }
      avatarUrl_ = "";
      regDate_ = 0L;
      postNum_ = 0;
      fame_ = 0L;
      signature_ = null;
      if (signatureBuilder_ != null) {
        signatureBuilder_.dispose();
        signatureBuilder_ = null;
      }
      nameRaw_ = "";
      mute_ = false;
      ipLocation_ = "";
      remote_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bugenzhao.mnga.protos.datamodel.DataModel.internal_static_User_descriptor;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.User getDefaultInstanceForType() {
      return com.bugenzhao.mnga.protos.datamodel.User.getDefaultInstance();
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.User build() {
      com.bugenzhao.mnga.protos.datamodel.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.datamodel.User buildPartial() {
      com.bugenzhao.mnga.protos.datamodel.User result = new com.bugenzhao.mnga.protos.datamodel.User(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bugenzhao.mnga.protos.datamodel.User result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = nameBuilder_ == null
            ? name_
            : nameBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.avatarUrl_ = avatarUrl_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.regDate_ = regDate_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.postNum_ = postNum_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.fame_ = fame_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.signature_ = signatureBuilder_ == null
            ? signature_
            : signatureBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.nameRaw_ = nameRaw_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.mute_ = mute_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.ipLocation_ = ipLocation_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.remote_ = remote_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bugenzhao.mnga.protos.datamodel.User) {
        return mergeFrom((com.bugenzhao.mnga.protos.datamodel.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bugenzhao.mnga.protos.datamodel.User other) {
      if (other == com.bugenzhao.mnga.protos.datamodel.User.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (!other.getAvatarUrl().isEmpty()) {
        avatarUrl_ = other.avatarUrl_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getRegDate() != 0L) {
        setRegDate(other.getRegDate());
      }
      if (other.getPostNum() != 0) {
        setPostNum(other.getPostNum());
      }
      if (other.getFame() != 0L) {
        setFame(other.getFame());
      }
      if (other.hasSignature()) {
        mergeSignature(other.getSignature());
      }
      if (!other.getNameRaw().isEmpty()) {
        nameRaw_ = other.nameRaw_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getMute() != false) {
        setMute(other.getMute());
      }
      if (!other.getIpLocation().isEmpty()) {
        ipLocation_ = other.ipLocation_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.getRemote() != false) {
        setRemote(other.getRemote());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              nameRaw_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 18
            case 26: {
              avatarUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              regDate_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              postNum_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              fame_ = input.readSInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              input.readMessage(
                  internalGetSignatureFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 66
            case 72: {
              mute_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              ipLocation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 88: {
              remote_ = input.readBool();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.bugenzhao.mnga.protos.datamodel.UserName name_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.UserName, com.bugenzhao.mnga.protos.datamodel.UserName.Builder, com.bugenzhao.mnga.protos.datamodel.UserNameOrBuilder> nameBuilder_;
    /**
     * <code>.UserName name = 8;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.UserName name = 8;</code>
     * @return The name.
     */
    public com.bugenzhao.mnga.protos.datamodel.UserName getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? com.bugenzhao.mnga.protos.datamodel.UserName.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserName name = 8;</code>
     */
    public Builder setName(com.bugenzhao.mnga.protos.datamodel.UserName value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
      } else {
        nameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.UserName name = 8;</code>
     */
    public Builder setName(
        com.bugenzhao.mnga.protos.datamodel.UserName.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.UserName name = 8;</code>
     */
    public Builder mergeName(com.bugenzhao.mnga.protos.datamodel.UserName value) {
      if (nameBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          name_ != null &&
          name_ != com.bugenzhao.mnga.protos.datamodel.UserName.getDefaultInstance()) {
          getNameBuilder().mergeFrom(value);
        } else {
          name_ = value;
        }
      } else {
        nameBuilder_.mergeFrom(value);
      }
      if (name_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.UserName name = 8;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = null;
      if (nameBuilder_ != null) {
        nameBuilder_.dispose();
        nameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.UserName name = 8;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.UserName.Builder getNameBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserName name = 8;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.UserNameOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            com.bugenzhao.mnga.protos.datamodel.UserName.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.UserName name = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.UserName, com.bugenzhao.mnga.protos.datamodel.UserName.Builder, com.bugenzhao.mnga.protos.datamodel.UserNameOrBuilder> 
        internalGetNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bugenzhao.mnga.protos.datamodel.UserName, com.bugenzhao.mnga.protos.datamodel.UserName.Builder, com.bugenzhao.mnga.protos.datamodel.UserNameOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private java.lang.Object avatarUrl_ = "";
    /**
     * <code>string avatar_url = 3;</code>
     * @return The avatarUrl.
     */
    public java.lang.String getAvatarUrl() {
      java.lang.Object ref = avatarUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatarUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string avatar_url = 3;</code>
     * @return The bytes for avatarUrl.
     */
    public com.google.protobuf.ByteString
        getAvatarUrlBytes() {
      java.lang.Object ref = avatarUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatarUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string avatar_url = 3;</code>
     * @param value The avatarUrl to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      avatarUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string avatar_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatarUrl() {
      avatarUrl_ = getDefaultInstance().getAvatarUrl();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string avatar_url = 3;</code>
     * @param value The bytes for avatarUrl to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      avatarUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long regDate_ ;
    /**
     * <pre>
     * The timestamp of the user's registration.
     * </pre>
     *
     * <code>uint64 reg_date = 4;</code>
     * @return The regDate.
     */
    @java.lang.Override
    public long getRegDate() {
      return regDate_;
    }
    /**
     * <pre>
     * The timestamp of the user's registration.
     * </pre>
     *
     * <code>uint64 reg_date = 4;</code>
     * @param value The regDate to set.
     * @return This builder for chaining.
     */
    public Builder setRegDate(long value) {

      regDate_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The timestamp of the user's registration.
     * </pre>
     *
     * <code>uint64 reg_date = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegDate() {
      bitField0_ = (bitField0_ & ~0x00000008);
      regDate_ = 0L;
      onChanged();
      return this;
    }

    private int postNum_ ;
    /**
     * <code>uint32 post_num = 5;</code>
     * @return The postNum.
     */
    @java.lang.Override
    public int getPostNum() {
      return postNum_;
    }
    /**
     * <code>uint32 post_num = 5;</code>
     * @param value The postNum to set.
     * @return This builder for chaining.
     */
    public Builder setPostNum(int value) {

      postNum_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 post_num = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPostNum() {
      bitField0_ = (bitField0_ & ~0x00000010);
      postNum_ = 0;
      onChanged();
      return this;
    }

    private long fame_ ;
    /**
     * <pre>
     * Should be resolved as `fame / 10`.
     * </pre>
     *
     * <code>sint64 fame = 6;</code>
     * @return The fame.
     */
    @java.lang.Override
    public long getFame() {
      return fame_;
    }
    /**
     * <pre>
     * Should be resolved as `fame / 10`.
     * </pre>
     *
     * <code>sint64 fame = 6;</code>
     * @param value The fame to set.
     * @return This builder for chaining.
     */
    public Builder setFame(long value) {

      fame_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Should be resolved as `fame / 10`.
     * </pre>
     *
     * <code>sint64 fame = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFame() {
      bitField0_ = (bitField0_ & ~0x00000020);
      fame_ = 0L;
      onChanged();
      return this;
    }

    private com.bugenzhao.mnga.protos.datamodel.PostContent signature_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.PostContent, com.bugenzhao.mnga.protos.datamodel.PostContent.Builder, com.bugenzhao.mnga.protos.datamodel.PostContentOrBuilder> signatureBuilder_;
    /**
     * <code>.PostContent signature = 7;</code>
     * @return Whether the signature field is set.
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.PostContent signature = 7;</code>
     * @return The signature.
     */
    public com.bugenzhao.mnga.protos.datamodel.PostContent getSignature() {
      if (signatureBuilder_ == null) {
        return signature_ == null ? com.bugenzhao.mnga.protos.datamodel.PostContent.getDefaultInstance() : signature_;
      } else {
        return signatureBuilder_.getMessage();
      }
    }
    /**
     * <code>.PostContent signature = 7;</code>
     */
    public Builder setSignature(com.bugenzhao.mnga.protos.datamodel.PostContent value) {
      if (signatureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signature_ = value;
      } else {
        signatureBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.PostContent signature = 7;</code>
     */
    public Builder setSignature(
        com.bugenzhao.mnga.protos.datamodel.PostContent.Builder builderForValue) {
      if (signatureBuilder_ == null) {
        signature_ = builderForValue.build();
      } else {
        signatureBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.PostContent signature = 7;</code>
     */
    public Builder mergeSignature(com.bugenzhao.mnga.protos.datamodel.PostContent value) {
      if (signatureBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          signature_ != null &&
          signature_ != com.bugenzhao.mnga.protos.datamodel.PostContent.getDefaultInstance()) {
          getSignatureBuilder().mergeFrom(value);
        } else {
          signature_ = value;
        }
      } else {
        signatureBuilder_.mergeFrom(value);
      }
      if (signature_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.PostContent signature = 7;</code>
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000040);
      signature_ = null;
      if (signatureBuilder_ != null) {
        signatureBuilder_.dispose();
        signatureBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.PostContent signature = 7;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.PostContent.Builder getSignatureBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetSignatureFieldBuilder().getBuilder();
    }
    /**
     * <code>.PostContent signature = 7;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.PostContentOrBuilder getSignatureOrBuilder() {
      if (signatureBuilder_ != null) {
        return signatureBuilder_.getMessageOrBuilder();
      } else {
        return signature_ == null ?
            com.bugenzhao.mnga.protos.datamodel.PostContent.getDefaultInstance() : signature_;
      }
    }
    /**
     * <code>.PostContent signature = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.PostContent, com.bugenzhao.mnga.protos.datamodel.PostContent.Builder, com.bugenzhao.mnga.protos.datamodel.PostContentOrBuilder> 
        internalGetSignatureFieldBuilder() {
      if (signatureBuilder_ == null) {
        signatureBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bugenzhao.mnga.protos.datamodel.PostContent, com.bugenzhao.mnga.protos.datamodel.PostContent.Builder, com.bugenzhao.mnga.protos.datamodel.PostContentOrBuilder>(
                getSignature(),
                getParentForChildren(),
                isClean());
        signature_ = null;
      }
      return signatureBuilder_;
    }

    private java.lang.Object nameRaw_ = "";
    /**
     * <code>string name_raw = 2 [deprecated = true];</code>
     * @deprecated User.name_raw is deprecated.
     *     See DataModel.proto;l=62
     * @return The nameRaw.
     */
    @java.lang.Deprecated public java.lang.String getNameRaw() {
      java.lang.Object ref = nameRaw_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameRaw_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name_raw = 2 [deprecated = true];</code>
     * @deprecated User.name_raw is deprecated.
     *     See DataModel.proto;l=62
     * @return The bytes for nameRaw.
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getNameRawBytes() {
      java.lang.Object ref = nameRaw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameRaw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name_raw = 2 [deprecated = true];</code>
     * @deprecated User.name_raw is deprecated.
     *     See DataModel.proto;l=62
     * @param value The nameRaw to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setNameRaw(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nameRaw_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string name_raw = 2 [deprecated = true];</code>
     * @deprecated User.name_raw is deprecated.
     *     See DataModel.proto;l=62
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder clearNameRaw() {
      nameRaw_ = getDefaultInstance().getNameRaw();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string name_raw = 2 [deprecated = true];</code>
     * @deprecated User.name_raw is deprecated.
     *     See DataModel.proto;l=62
     * @param value The bytes for nameRaw to set.
     * @return This builder for chaining.
     */
    @java.lang.Deprecated public Builder setNameRawBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nameRaw_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private boolean mute_ ;
    /**
     * <pre>
     * Whether the user is temporarily banned by NGA.
     * </pre>
     *
     * <code>bool mute = 9;</code>
     * @return The mute.
     */
    @java.lang.Override
    public boolean getMute() {
      return mute_;
    }
    /**
     * <pre>
     * Whether the user is temporarily banned by NGA.
     * </pre>
     *
     * <code>bool mute = 9;</code>
     * @param value The mute to set.
     * @return This builder for chaining.
     */
    public Builder setMute(boolean value) {

      mute_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the user is temporarily banned by NGA.
     * </pre>
     *
     * <code>bool mute = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMute() {
      bitField0_ = (bitField0_ & ~0x00000100);
      mute_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object ipLocation_ = "";
    /**
     * <code>string ip_location = 10;</code>
     * @return The ipLocation.
     */
    public java.lang.String getIpLocation() {
      java.lang.Object ref = ipLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ip_location = 10;</code>
     * @return The bytes for ipLocation.
     */
    public com.google.protobuf.ByteString
        getIpLocationBytes() {
      java.lang.Object ref = ipLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip_location = 10;</code>
     * @param value The ipLocation to set.
     * @return This builder for chaining.
     */
    public Builder setIpLocation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ipLocation_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string ip_location = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIpLocation() {
      ipLocation_ = getDefaultInstance().getIpLocation();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string ip_location = 10;</code>
     * @param value The bytes for ipLocation to set.
     * @return This builder for chaining.
     */
    public Builder setIpLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ipLocation_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private boolean remote_ ;
    /**
     * <pre>
     * Whether this user info is fetched with a separate `remoteUser` call.
     * </pre>
     *
     * <code>bool remote = 11;</code>
     * @return The remote.
     */
    @java.lang.Override
    public boolean getRemote() {
      return remote_;
    }
    /**
     * <pre>
     * Whether this user info is fetched with a separate `remoteUser` call.
     * </pre>
     *
     * <code>bool remote = 11;</code>
     * @param value The remote to set.
     * @return This builder for chaining.
     */
    public Builder setRemote(boolean value) {

      remote_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether this user info is fetched with a separate `remoteUser` call.
     * </pre>
     *
     * <code>bool remote = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemote() {
      bitField0_ = (bitField0_ & ~0x00000400);
      remote_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:User)
  }

  // @@protoc_insertion_point(class_scope:User)
  private static final com.bugenzhao.mnga.protos.datamodel.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bugenzhao.mnga.protos.datamodel.User();
  }

  public static com.bugenzhao.mnga.protos.datamodel.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

