// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializeasyncRequest")
public inline fun asyncRequest(block: com.bugenzhao.mnga.protos.service.AsyncRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.AsyncRequest =
  com.bugenzhao.mnga.protos.service.AsyncRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.AsyncRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * Asynchronous services that are called in callback manner.
 * ```
 *
 * Protobuf type `AsyncRequest`
 */
public object AsyncRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.AsyncRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.AsyncRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.AsyncRequest = _builder.build()

    /**
     * ```
     * Get topics in given forum.
     * ```
     *
     * `.TopicListRequest topic_list = 1;`
     */
    public var topicList: com.bugenzhao.mnga.protos.service.TopicListRequest
      @kotlin.jvm.JvmName("getTopicList")
        get() = _builder.topicList
      @kotlin.jvm.JvmName("setTopicList")
        set(value) {
        _builder.topicList = value
      }
    /**
     * ```
     * Get topics in given forum.
     * ```
     *
     * `.TopicListRequest topic_list = 1;`
     */
    public fun clearTopicList() {
      _builder.clearTopicList()
    }
    /**
     * ```
     * Get topics in given forum.
     * ```
     *
     * `.TopicListRequest topic_list = 1;`
     * @return Whether the topicList field is set.
     */
    public fun hasTopicList(): kotlin.Boolean {
      return _builder.hasTopicList()
    }

    /**
     * ```
     * Get posts in given topic.
     * ```
     *
     * `.TopicDetailsRequest topic_details = 2;`
     */
    public var topicDetails: com.bugenzhao.mnga.protos.service.TopicDetailsRequest
      @kotlin.jvm.JvmName("getTopicDetails")
        get() = _builder.topicDetails
      @kotlin.jvm.JvmName("setTopicDetails")
        set(value) {
        _builder.topicDetails = value
      }
    /**
     * ```
     * Get posts in given topic.
     * ```
     *
     * `.TopicDetailsRequest topic_details = 2;`
     */
    public fun clearTopicDetails() {
      _builder.clearTopicDetails()
    }
    /**
     * ```
     * Get posts in given topic.
     * ```
     *
     * `.TopicDetailsRequest topic_details = 2;`
     * @return Whether the topicDetails field is set.
     */
    public fun hasTopicDetails(): kotlin.Boolean {
      return _builder.hasTopicDetails()
    }

    /**
     * ```
     * Set filter for subforums.
     * ```
     *
     * `.SubforumFilterRequest subforum_filter = 3;`
     */
    public var subforumFilter: com.bugenzhao.mnga.protos.service.SubforumFilterRequest
      @kotlin.jvm.JvmName("getSubforumFilter")
        get() = _builder.subforumFilter
      @kotlin.jvm.JvmName("setSubforumFilter")
        set(value) {
        _builder.subforumFilter = value
      }
    /**
     * ```
     * Set filter for subforums.
     * ```
     *
     * `.SubforumFilterRequest subforum_filter = 3;`
     */
    public fun clearSubforumFilter() {
      _builder.clearSubforumFilter()
    }
    /**
     * ```
     * Set filter for subforums.
     * ```
     *
     * `.SubforumFilterRequest subforum_filter = 3;`
     * @return Whether the subforumFilter field is set.
     */
    public fun hasSubforumFilter(): kotlin.Boolean {
      return _builder.hasSubforumFilter()
    }

    /**
     * ```
     * Get all forums.
     * ```
     *
     * `.ForumListRequest forum_list = 4;`
     */
    public var forumList: com.bugenzhao.mnga.protos.service.ForumListRequest
      @kotlin.jvm.JvmName("getForumList")
        get() = _builder.forumList
      @kotlin.jvm.JvmName("setForumList")
        set(value) {
        _builder.forumList = value
      }
    /**
     * ```
     * Get all forums.
     * ```
     *
     * `.ForumListRequest forum_list = 4;`
     */
    public fun clearForumList() {
      _builder.clearForumList()
    }
    /**
     * ```
     * Get all forums.
     * ```
     *
     * `.ForumListRequest forum_list = 4;`
     * @return Whether the forumList field is set.
     */
    public fun hasForumList(): kotlin.Boolean {
      return _builder.hasForumList()
    }

    /**
     * ```
     * Find user info remotely.
     * ```
     *
     * `.RemoteUserRequest remote_user = 5;`
     */
    public var remoteUser: com.bugenzhao.mnga.protos.service.RemoteUserRequest
      @kotlin.jvm.JvmName("getRemoteUser")
        get() = _builder.remoteUser
      @kotlin.jvm.JvmName("setRemoteUser")
        set(value) {
        _builder.remoteUser = value
      }
    /**
     * ```
     * Find user info remotely.
     * ```
     *
     * `.RemoteUserRequest remote_user = 5;`
     */
    public fun clearRemoteUser() {
      _builder.clearRemoteUser()
    }
    /**
     * ```
     * Find user info remotely.
     * ```
     *
     * `.RemoteUserRequest remote_user = 5;`
     * @return Whether the remoteUser field is set.
     */
    public fun hasRemoteUser(): kotlin.Boolean {
      return _builder.hasRemoteUser()
    }

    /**
     * ```
     * Do voting to posts.
     * ```
     *
     * `.PostVoteRequest post_vote = 6;`
     */
    public var postVote: com.bugenzhao.mnga.protos.service.PostVoteRequest
      @kotlin.jvm.JvmName("getPostVote")
        get() = _builder.postVote
      @kotlin.jvm.JvmName("setPostVote")
        set(value) {
        _builder.postVote = value
      }
    /**
     * ```
     * Do voting to posts.
     * ```
     *
     * `.PostVoteRequest post_vote = 6;`
     */
    public fun clearPostVote() {
      _builder.clearPostVote()
    }
    /**
     * ```
     * Do voting to posts.
     * ```
     *
     * `.PostVoteRequest post_vote = 6;`
     * @return Whether the postVote field is set.
     */
    public fun hasPostVote(): kotlin.Boolean {
      return _builder.hasPostVote()
    }

    /**
     * ```
     * Get history of visited topics.
     * ```
     *
     * `.TopicHistoryRequest topic_history = 7;`
     */
    public var topicHistory: com.bugenzhao.mnga.protos.service.TopicHistoryRequest
      @kotlin.jvm.JvmName("getTopicHistory")
        get() = _builder.topicHistory
      @kotlin.jvm.JvmName("setTopicHistory")
        set(value) {
        _builder.topicHistory = value
      }
    /**
     * ```
     * Get history of visited topics.
     * ```
     *
     * `.TopicHistoryRequest topic_history = 7;`
     */
    public fun clearTopicHistory() {
      _builder.clearTopicHistory()
    }
    /**
     * ```
     * Get history of visited topics.
     * ```
     *
     * `.TopicHistoryRequest topic_history = 7;`
     * @return Whether the topicHistory field is set.
     */
    public fun hasTopicHistory(): kotlin.Boolean {
      return _builder.hasTopicHistory()
    }

    /**
     * ```
     * Get hot topics in given forum.
     * ```
     *
     * `.HotTopicListRequest hot_topic_list = 8;`
     */
    public var hotTopicList: com.bugenzhao.mnga.protos.service.HotTopicListRequest
      @kotlin.jvm.JvmName("getHotTopicList")
        get() = _builder.hotTopicList
      @kotlin.jvm.JvmName("setHotTopicList")
        set(value) {
        _builder.hotTopicList = value
      }
    /**
     * ```
     * Get hot topics in given forum.
     * ```
     *
     * `.HotTopicListRequest hot_topic_list = 8;`
     */
    public fun clearHotTopicList() {
      _builder.clearHotTopicList()
    }
    /**
     * ```
     * Get hot topics in given forum.
     * ```
     *
     * `.HotTopicListRequest hot_topic_list = 8;`
     * @return Whether the hotTopicList field is set.
     */
    public fun hasHotTopicList(): kotlin.Boolean {
      return _builder.hasHotTopicList()
    }

    /**
     * ```
     * Search for a specific forum.
     * ```
     *
     * `.ForumSearchRequest forum_search = 9;`
     */
    public var forumSearch: com.bugenzhao.mnga.protos.service.ForumSearchRequest
      @kotlin.jvm.JvmName("getForumSearch")
        get() = _builder.forumSearch
      @kotlin.jvm.JvmName("setForumSearch")
        set(value) {
        _builder.forumSearch = value
      }
    /**
     * ```
     * Search for a specific forum.
     * ```
     *
     * `.ForumSearchRequest forum_search = 9;`
     */
    public fun clearForumSearch() {
      _builder.clearForumSearch()
    }
    /**
     * ```
     * Search for a specific forum.
     * ```
     *
     * `.ForumSearchRequest forum_search = 9;`
     * @return Whether the forumSearch field is set.
     */
    public fun hasForumSearch(): kotlin.Boolean {
      return _builder.hasForumSearch()
    }

    /**
     * ```
     * Get favorite topics.
     * ```
     *
     * `.FavoriteTopicListRequest favorite_topic_list = 10;`
     */
    public var favoriteTopicList: com.bugenzhao.mnga.protos.service.FavoriteTopicListRequest
      @kotlin.jvm.JvmName("getFavoriteTopicList")
        get() = _builder.favoriteTopicList
      @kotlin.jvm.JvmName("setFavoriteTopicList")
        set(value) {
        _builder.favoriteTopicList = value
      }
    /**
     * ```
     * Get favorite topics.
     * ```
     *
     * `.FavoriteTopicListRequest favorite_topic_list = 10;`
     */
    public fun clearFavoriteTopicList() {
      _builder.clearFavoriteTopicList()
    }
    /**
     * ```
     * Get favorite topics.
     * ```
     *
     * `.FavoriteTopicListRequest favorite_topic_list = 10;`
     * @return Whether the favoriteTopicList field is set.
     */
    public fun hasFavoriteTopicList(): kotlin.Boolean {
      return _builder.hasFavoriteTopicList()
    }

    /**
     * ```
     * Mark a topic as favored.
     * ```
     *
     * `.TopicFavorRequest topic_favor = 11;`
     */
    public var topicFavor: com.bugenzhao.mnga.protos.service.TopicFavorRequest
      @kotlin.jvm.JvmName("getTopicFavor")
        get() = _builder.topicFavor
      @kotlin.jvm.JvmName("setTopicFavor")
        set(value) {
        _builder.topicFavor = value
      }
    /**
     * ```
     * Mark a topic as favored.
     * ```
     *
     * `.TopicFavorRequest topic_favor = 11;`
     */
    public fun clearTopicFavor() {
      _builder.clearTopicFavor()
    }
    /**
     * ```
     * Mark a topic as favored.
     * ```
     *
     * `.TopicFavorRequest topic_favor = 11;`
     * @return Whether the topicFavor field is set.
     */
    public fun hasTopicFavor(): kotlin.Boolean {
      return _builder.hasTopicFavor()
    }

    /**
     * ```
     * Fetch the initial content for a posting action.
     * ```
     *
     * `.PostReplyFetchContentRequest post_reply_fetch_content = 12;`
     */
    public var postReplyFetchContent: com.bugenzhao.mnga.protos.service.PostReplyFetchContentRequest
      @kotlin.jvm.JvmName("getPostReplyFetchContent")
        get() = _builder.postReplyFetchContent
      @kotlin.jvm.JvmName("setPostReplyFetchContent")
        set(value) {
        _builder.postReplyFetchContent = value
      }
    /**
     * ```
     * Fetch the initial content for a posting action.
     * ```
     *
     * `.PostReplyFetchContentRequest post_reply_fetch_content = 12;`
     */
    public fun clearPostReplyFetchContent() {
      _builder.clearPostReplyFetchContent()
    }
    /**
     * ```
     * Fetch the initial content for a posting action.
     * ```
     *
     * `.PostReplyFetchContentRequest post_reply_fetch_content = 12;`
     * @return Whether the postReplyFetchContent field is set.
     */
    public fun hasPostReplyFetchContent(): kotlin.Boolean {
      return _builder.hasPostReplyFetchContent()
    }

    /**
     * ```
     * Do posting to some topic or forum.
     * ```
     *
     * `.PostReplyRequest post_reply = 13;`
     */
    public var postReply: com.bugenzhao.mnga.protos.service.PostReplyRequest
      @kotlin.jvm.JvmName("getPostReply")
        get() = _builder.postReply
      @kotlin.jvm.JvmName("setPostReply")
        set(value) {
        _builder.postReply = value
      }
    /**
     * ```
     * Do posting to some topic or forum.
     * ```
     *
     * `.PostReplyRequest post_reply = 13;`
     */
    public fun clearPostReply() {
      _builder.clearPostReply()
    }
    /**
     * ```
     * Do posting to some topic or forum.
     * ```
     *
     * `.PostReplyRequest post_reply = 13;`
     * @return Whether the postReply field is set.
     */
    public fun hasPostReply(): kotlin.Boolean {
      return _builder.hasPostReply()
    }

    /**
     * ```
     * Get all notifications.
     * ```
     *
     * `.FetchNotificationRequest fetch_notification = 14;`
     */
    public var fetchNotification: com.bugenzhao.mnga.protos.service.FetchNotificationRequest
      @kotlin.jvm.JvmName("getFetchNotification")
        get() = _builder.fetchNotification
      @kotlin.jvm.JvmName("setFetchNotification")
        set(value) {
        _builder.fetchNotification = value
      }
    /**
     * ```
     * Get all notifications.
     * ```
     *
     * `.FetchNotificationRequest fetch_notification = 14;`
     */
    public fun clearFetchNotification() {
      _builder.clearFetchNotification()
    }
    /**
     * ```
     * Get all notifications.
     * ```
     *
     * `.FetchNotificationRequest fetch_notification = 14;`
     * @return Whether the fetchNotification field is set.
     */
    public fun hasFetchNotification(): kotlin.Boolean {
      return _builder.hasFetchNotification()
    }

    /**
     * ```
     * Upload attachments before posting.
     * ```
     *
     * `.UploadAttachmentRequest upload_attachment = 15;`
     */
    public var uploadAttachment: com.bugenzhao.mnga.protos.service.UploadAttachmentRequest
      @kotlin.jvm.JvmName("getUploadAttachment")
        get() = _builder.uploadAttachment
      @kotlin.jvm.JvmName("setUploadAttachment")
        set(value) {
        _builder.uploadAttachment = value
      }
    /**
     * ```
     * Upload attachments before posting.
     * ```
     *
     * `.UploadAttachmentRequest upload_attachment = 15;`
     */
    public fun clearUploadAttachment() {
      _builder.clearUploadAttachment()
    }
    /**
     * ```
     * Upload attachments before posting.
     * ```
     *
     * `.UploadAttachmentRequest upload_attachment = 15;`
     * @return Whether the uploadAttachment field is set.
     */
    public fun hasUploadAttachment(): kotlin.Boolean {
      return _builder.hasUploadAttachment()
    }

    /**
     * ```
     * Get topics of given user.
     * ```
     *
     * `.UserTopicListRequest user_topic_list = 16;`
     */
    public var userTopicList: com.bugenzhao.mnga.protos.service.UserTopicListRequest
      @kotlin.jvm.JvmName("getUserTopicList")
        get() = _builder.userTopicList
      @kotlin.jvm.JvmName("setUserTopicList")
        set(value) {
        _builder.userTopicList = value
      }
    /**
     * ```
     * Get topics of given user.
     * ```
     *
     * `.UserTopicListRequest user_topic_list = 16;`
     */
    public fun clearUserTopicList() {
      _builder.clearUserTopicList()
    }
    /**
     * ```
     * Get topics of given user.
     * ```
     *
     * `.UserTopicListRequest user_topic_list = 16;`
     * @return Whether the userTopicList field is set.
     */
    public fun hasUserTopicList(): kotlin.Boolean {
      return _builder.hasUserTopicList()
    }

    /**
     * ```
     * Get posts of given user.
     * ```
     *
     * `.UserPostListRequest user_post_list = 17;`
     */
    public var userPostList: com.bugenzhao.mnga.protos.service.UserPostListRequest
      @kotlin.jvm.JvmName("getUserPostList")
        get() = _builder.userPostList
      @kotlin.jvm.JvmName("setUserPostList")
        set(value) {
        _builder.userPostList = value
      }
    /**
     * ```
     * Get posts of given user.
     * ```
     *
     * `.UserPostListRequest user_post_list = 17;`
     */
    public fun clearUserPostList() {
      _builder.clearUserPostList()
    }
    /**
     * ```
     * Get posts of given user.
     * ```
     *
     * `.UserPostListRequest user_post_list = 17;`
     * @return Whether the userPostList field is set.
     */
    public fun hasUserPostList(): kotlin.Boolean {
      return _builder.hasUserPostList()
    }

    /**
     * ```
     * Get short message conversations of current user.
     * ```
     *
     * `.ShortMessageListRequest short_message_list = 18;`
     */
    public var shortMessageList: com.bugenzhao.mnga.protos.service.ShortMessageListRequest
      @kotlin.jvm.JvmName("getShortMessageList")
        get() = _builder.shortMessageList
      @kotlin.jvm.JvmName("setShortMessageList")
        set(value) {
        _builder.shortMessageList = value
      }
    /**
     * ```
     * Get short message conversations of current user.
     * ```
     *
     * `.ShortMessageListRequest short_message_list = 18;`
     */
    public fun clearShortMessageList() {
      _builder.clearShortMessageList()
    }
    /**
     * ```
     * Get short message conversations of current user.
     * ```
     *
     * `.ShortMessageListRequest short_message_list = 18;`
     * @return Whether the shortMessageList field is set.
     */
    public fun hasShortMessageList(): kotlin.Boolean {
      return _builder.hasShortMessageList()
    }

    /**
     * ```
     * Get short message posts of a conversation.
     * ```
     *
     * `.ShortMessageDetailsRequest short_message_details = 19;`
     */
    public var shortMessageDetails: com.bugenzhao.mnga.protos.service.ShortMessageDetailsRequest
      @kotlin.jvm.JvmName("getShortMessageDetails")
        get() = _builder.shortMessageDetails
      @kotlin.jvm.JvmName("setShortMessageDetails")
        set(value) {
        _builder.shortMessageDetails = value
      }
    /**
     * ```
     * Get short message posts of a conversation.
     * ```
     *
     * `.ShortMessageDetailsRequest short_message_details = 19;`
     */
    public fun clearShortMessageDetails() {
      _builder.clearShortMessageDetails()
    }
    /**
     * ```
     * Get short message posts of a conversation.
     * ```
     *
     * `.ShortMessageDetailsRequest short_message_details = 19;`
     * @return Whether the shortMessageDetails field is set.
     */
    public fun hasShortMessageDetails(): kotlin.Boolean {
      return _builder.hasShortMessageDetails()
    }

    /**
     * ```
     * Do posting to some short message post or conversation.
     * ```
     *
     * `.ShortMessagePostRequest short_message_post = 20;`
     */
    public var shortMessagePost: com.bugenzhao.mnga.protos.service.ShortMessagePostRequest
      @kotlin.jvm.JvmName("getShortMessagePost")
        get() = _builder.shortMessagePost
      @kotlin.jvm.JvmName("setShortMessagePost")
        set(value) {
        _builder.shortMessagePost = value
      }
    /**
     * ```
     * Do posting to some short message post or conversation.
     * ```
     *
     * `.ShortMessagePostRequest short_message_post = 20;`
     */
    public fun clearShortMessagePost() {
      _builder.clearShortMessagePost()
    }
    /**
     * ```
     * Do posting to some short message post or conversation.
     * ```
     *
     * `.ShortMessagePostRequest short_message_post = 20;`
     * @return Whether the shortMessagePost field is set.
     */
    public fun hasShortMessagePost(): kotlin.Boolean {
      return _builder.hasShortMessagePost()
    }

    /**
     * ```
     * Search for topics with some keyword in specific forum or all forums.
     * ```
     *
     * `.TopicSearchRequest topic_search = 21;`
     */
    public var topicSearch: com.bugenzhao.mnga.protos.service.TopicSearchRequest
      @kotlin.jvm.JvmName("getTopicSearch")
        get() = _builder.topicSearch
      @kotlin.jvm.JvmName("setTopicSearch")
        set(value) {
        _builder.topicSearch = value
      }
    /**
     * ```
     * Search for topics with some keyword in specific forum or all forums.
     * ```
     *
     * `.TopicSearchRequest topic_search = 21;`
     */
    public fun clearTopicSearch() {
      _builder.clearTopicSearch()
    }
    /**
     * ```
     * Search for topics with some keyword in specific forum or all forums.
     * ```
     *
     * `.TopicSearchRequest topic_search = 21;`
     * @return Whether the topicSearch field is set.
     */
    public fun hasTopicSearch(): kotlin.Boolean {
      return _builder.hasTopicSearch()
    }

    /**
     * ```
     * Sign in (clock in) for today.
     * ```
     *
     * `.ClockInRequest clock_in = 22;`
     */
    public var clockIn: com.bugenzhao.mnga.protos.service.ClockInRequest
      @kotlin.jvm.JvmName("getClockIn")
        get() = _builder.clockIn
      @kotlin.jvm.JvmName("setClockIn")
        set(value) {
        _builder.clockIn = value
      }
    /**
     * ```
     * Sign in (clock in) for today.
     * ```
     *
     * `.ClockInRequest clock_in = 22;`
     */
    public fun clearClockIn() {
      _builder.clearClockIn()
    }
    /**
     * ```
     * Sign in (clock in) for today.
     * ```
     *
     * `.ClockInRequest clock_in = 22;`
     * @return Whether the clockIn field is set.
     */
    public fun hasClockIn(): kotlin.Boolean {
      return _builder.hasClockIn()
    }

    /**
     * ```
     * Clear or check the cache.
     * ```
     *
     * `.CacheRequest cache = 23;`
     */
    public var cache: com.bugenzhao.mnga.protos.service.CacheRequest
      @kotlin.jvm.JvmName("getCache")
        get() = _builder.cache
      @kotlin.jvm.JvmName("setCache")
        set(value) {
        _builder.cache = value
      }
    /**
     * ```
     * Clear or check the cache.
     * ```
     *
     * `.CacheRequest cache = 23;`
     */
    public fun clearCache() {
      _builder.clearCache()
    }
    /**
     * ```
     * Clear or check the cache.
     * ```
     *
     * `.CacheRequest cache = 23;`
     * @return Whether the cache field is set.
     */
    public fun hasCache(): kotlin.Boolean {
      return _builder.hasCache()
    }

    /**
     * ```
     * List favorite topic folders.
     * ```
     *
     * `.FavoriteFolderListRequest favorite_folder_list = 24;`
     */
    public var favoriteFolderList: com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest
      @kotlin.jvm.JvmName("getFavoriteFolderList")
        get() = _builder.favoriteFolderList
      @kotlin.jvm.JvmName("setFavoriteFolderList")
        set(value) {
        _builder.favoriteFolderList = value
      }
    /**
     * ```
     * List favorite topic folders.
     * ```
     *
     * `.FavoriteFolderListRequest favorite_folder_list = 24;`
     */
    public fun clearFavoriteFolderList() {
      _builder.clearFavoriteFolderList()
    }
    /**
     * ```
     * List favorite topic folders.
     * ```
     *
     * `.FavoriteFolderListRequest favorite_folder_list = 24;`
     * @return Whether the favoriteFolderList field is set.
     */
    public fun hasFavoriteFolderList(): kotlin.Boolean {
      return _builder.hasFavoriteFolderList()
    }

    /**
     * ```
     * Modify a favorite topic folder.
     * ```
     *
     * `.FavoriteFolderModifyRequest favorite_folder_modify = 25;`
     */
    public var favoriteFolderModify: com.bugenzhao.mnga.protos.service.FavoriteFolderModifyRequest
      @kotlin.jvm.JvmName("getFavoriteFolderModify")
        get() = _builder.favoriteFolderModify
      @kotlin.jvm.JvmName("setFavoriteFolderModify")
        set(value) {
        _builder.favoriteFolderModify = value
      }
    /**
     * ```
     * Modify a favorite topic folder.
     * ```
     *
     * `.FavoriteFolderModifyRequest favorite_folder_modify = 25;`
     */
    public fun clearFavoriteFolderModify() {
      _builder.clearFavoriteFolderModify()
    }
    /**
     * ```
     * Modify a favorite topic folder.
     * ```
     *
     * `.FavoriteFolderModifyRequest favorite_folder_modify = 25;`
     * @return Whether the favoriteFolderModify field is set.
     */
    public fun hasFavoriteFolderModify(): kotlin.Boolean {
      return _builder.hasFavoriteFolderModify()
    }

    /**
     * ```
     * Create a favorite topic folder.
     * ```
     *
     * `.FavoriteFolderCreateRequest favorite_folder_create = 26;`
     */
    public var favoriteFolderCreate: com.bugenzhao.mnga.protos.service.FavoriteFolderCreateRequest
      @kotlin.jvm.JvmName("getFavoriteFolderCreate")
        get() = _builder.favoriteFolderCreate
      @kotlin.jvm.JvmName("setFavoriteFolderCreate")
        set(value) {
        _builder.favoriteFolderCreate = value
      }
    /**
     * ```
     * Create a favorite topic folder.
     * ```
     *
     * `.FavoriteFolderCreateRequest favorite_folder_create = 26;`
     */
    public fun clearFavoriteFolderCreate() {
      _builder.clearFavoriteFolderCreate()
    }
    /**
     * ```
     * Create a favorite topic folder.
     * ```
     *
     * `.FavoriteFolderCreateRequest favorite_folder_create = 26;`
     * @return Whether the favoriteFolderCreate field is set.
     */
    public fun hasFavoriteFolderCreate(): kotlin.Boolean {
      return _builder.hasFavoriteFolderCreate()
    }

    /**
     * ```
     * Update the signature of the current user.
     * ```
     *
     * `.UserSignatureUpdateRequest user_signature_update = 27;`
     */
    public var userSignatureUpdate: com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest
      @kotlin.jvm.JvmName("getUserSignatureUpdate")
        get() = _builder.userSignatureUpdate
      @kotlin.jvm.JvmName("setUserSignatureUpdate")
        set(value) {
        _builder.userSignatureUpdate = value
      }
    /**
     * ```
     * Update the signature of the current user.
     * ```
     *
     * `.UserSignatureUpdateRequest user_signature_update = 27;`
     */
    public fun clearUserSignatureUpdate() {
      _builder.clearUserSignatureUpdate()
    }
    /**
     * ```
     * Update the signature of the current user.
     * ```
     *
     * `.UserSignatureUpdateRequest user_signature_update = 27;`
     * @return Whether the userSignatureUpdate field is set.
     */
    public fun hasUserSignatureUpdate(): kotlin.Boolean {
      return _builder.hasUserSignatureUpdate()
    }

    /**
     * ```
     * Get favorite forums (forum_favor2).
     * ```
     *
     * `.FavoriteForumListRequest favorite_forum_list = 28;`
     */
    public var favoriteForumList: com.bugenzhao.mnga.protos.service.FavoriteForumListRequest
      @kotlin.jvm.JvmName("getFavoriteForumList")
        get() = _builder.favoriteForumList
      @kotlin.jvm.JvmName("setFavoriteForumList")
        set(value) {
        _builder.favoriteForumList = value
      }
    /**
     * ```
     * Get favorite forums (forum_favor2).
     * ```
     *
     * `.FavoriteForumListRequest favorite_forum_list = 28;`
     */
    public fun clearFavoriteForumList() {
      _builder.clearFavoriteForumList()
    }
    /**
     * ```
     * Get favorite forums (forum_favor2).
     * ```
     *
     * `.FavoriteForumListRequest favorite_forum_list = 28;`
     * @return Whether the favoriteForumList field is set.
     */
    public fun hasFavoriteForumList(): kotlin.Boolean {
      return _builder.hasFavoriteForumList()
    }

    /**
     * ```
     * Add or remove a favorite forum (forum_favor2).
     * ```
     *
     * `.FavoriteForumModifyRequest favorite_forum_modify = 29;`
     */
    public var favoriteForumModify: com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest
      @kotlin.jvm.JvmName("getFavoriteForumModify")
        get() = _builder.favoriteForumModify
      @kotlin.jvm.JvmName("setFavoriteForumModify")
        set(value) {
        _builder.favoriteForumModify = value
      }
    /**
     * ```
     * Add or remove a favorite forum (forum_favor2).
     * ```
     *
     * `.FavoriteForumModifyRequest favorite_forum_modify = 29;`
     */
    public fun clearFavoriteForumModify() {
      _builder.clearFavoriteForumModify()
    }
    /**
     * ```
     * Add or remove a favorite forum (forum_favor2).
     * ```
     *
     * `.FavoriteForumModifyRequest favorite_forum_modify = 29;`
     * @return Whether the favoriteForumModify field is set.
     */
    public fun hasFavoriteForumModify(): kotlin.Boolean {
      return _builder.hasFavoriteForumModify()
    }

    /**
     * ```
     * Query clock-in stats only (no sign-in side effect).
     * ```
     *
     * `.ClockInStatsRequest clock_in_stats = 30;`
     */
    public var clockInStats: com.bugenzhao.mnga.protos.service.ClockInStatsRequest
      @kotlin.jvm.JvmName("getClockInStats")
        get() = _builder.clockInStats
      @kotlin.jvm.JvmName("setClockInStats")
        set(value) {
        _builder.clockInStats = value
      }
    /**
     * ```
     * Query clock-in stats only (no sign-in side effect).
     * ```
     *
     * `.ClockInStatsRequest clock_in_stats = 30;`
     */
    public fun clearClockInStats() {
      _builder.clearClockInStats()
    }
    /**
     * ```
     * Query clock-in stats only (no sign-in side effect).
     * ```
     *
     * `.ClockInStatsRequest clock_in_stats = 30;`
     * @return Whether the clockInStats field is set.
     */
    public fun hasClockInStats(): kotlin.Boolean {
      return _builder.hasClockInStats()
    }
    public val valueCase: com.bugenzhao.mnga.protos.service.AsyncRequest.ValueCase
    @kotlin.jvm.JvmName("getValueCase")
      get() = _builder.getValueCase()

    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.AsyncRequest.copy(block: `com.bugenzhao.mnga.protos.service`.AsyncRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.AsyncRequest =
  `com.bugenzhao.mnga.protos.service`.AsyncRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.topicListOrNull: com.bugenzhao.mnga.protos.service.TopicListRequest?
  get() = if (hasTopicList()) getTopicList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.topicDetailsOrNull: com.bugenzhao.mnga.protos.service.TopicDetailsRequest?
  get() = if (hasTopicDetails()) getTopicDetails() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.subforumFilterOrNull: com.bugenzhao.mnga.protos.service.SubforumFilterRequest?
  get() = if (hasSubforumFilter()) getSubforumFilter() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.forumListOrNull: com.bugenzhao.mnga.protos.service.ForumListRequest?
  get() = if (hasForumList()) getForumList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.remoteUserOrNull: com.bugenzhao.mnga.protos.service.RemoteUserRequest?
  get() = if (hasRemoteUser()) getRemoteUser() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.postVoteOrNull: com.bugenzhao.mnga.protos.service.PostVoteRequest?
  get() = if (hasPostVote()) getPostVote() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.topicHistoryOrNull: com.bugenzhao.mnga.protos.service.TopicHistoryRequest?
  get() = if (hasTopicHistory()) getTopicHistory() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.hotTopicListOrNull: com.bugenzhao.mnga.protos.service.HotTopicListRequest?
  get() = if (hasHotTopicList()) getHotTopicList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.forumSearchOrNull: com.bugenzhao.mnga.protos.service.ForumSearchRequest?
  get() = if (hasForumSearch()) getForumSearch() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.favoriteTopicListOrNull: com.bugenzhao.mnga.protos.service.FavoriteTopicListRequest?
  get() = if (hasFavoriteTopicList()) getFavoriteTopicList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.topicFavorOrNull: com.bugenzhao.mnga.protos.service.TopicFavorRequest?
  get() = if (hasTopicFavor()) getTopicFavor() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.postReplyFetchContentOrNull: com.bugenzhao.mnga.protos.service.PostReplyFetchContentRequest?
  get() = if (hasPostReplyFetchContent()) getPostReplyFetchContent() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.postReplyOrNull: com.bugenzhao.mnga.protos.service.PostReplyRequest?
  get() = if (hasPostReply()) getPostReply() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.fetchNotificationOrNull: com.bugenzhao.mnga.protos.service.FetchNotificationRequest?
  get() = if (hasFetchNotification()) getFetchNotification() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.uploadAttachmentOrNull: com.bugenzhao.mnga.protos.service.UploadAttachmentRequest?
  get() = if (hasUploadAttachment()) getUploadAttachment() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.userTopicListOrNull: com.bugenzhao.mnga.protos.service.UserTopicListRequest?
  get() = if (hasUserTopicList()) getUserTopicList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.userPostListOrNull: com.bugenzhao.mnga.protos.service.UserPostListRequest?
  get() = if (hasUserPostList()) getUserPostList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.shortMessageListOrNull: com.bugenzhao.mnga.protos.service.ShortMessageListRequest?
  get() = if (hasShortMessageList()) getShortMessageList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.shortMessageDetailsOrNull: com.bugenzhao.mnga.protos.service.ShortMessageDetailsRequest?
  get() = if (hasShortMessageDetails()) getShortMessageDetails() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.shortMessagePostOrNull: com.bugenzhao.mnga.protos.service.ShortMessagePostRequest?
  get() = if (hasShortMessagePost()) getShortMessagePost() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.topicSearchOrNull: com.bugenzhao.mnga.protos.service.TopicSearchRequest?
  get() = if (hasTopicSearch()) getTopicSearch() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.clockInOrNull: com.bugenzhao.mnga.protos.service.ClockInRequest?
  get() = if (hasClockIn()) getClockIn() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.cacheOrNull: com.bugenzhao.mnga.protos.service.CacheRequest?
  get() = if (hasCache()) getCache() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.favoriteFolderListOrNull: com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest?
  get() = if (hasFavoriteFolderList()) getFavoriteFolderList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.favoriteFolderModifyOrNull: com.bugenzhao.mnga.protos.service.FavoriteFolderModifyRequest?
  get() = if (hasFavoriteFolderModify()) getFavoriteFolderModify() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.favoriteFolderCreateOrNull: com.bugenzhao.mnga.protos.service.FavoriteFolderCreateRequest?
  get() = if (hasFavoriteFolderCreate()) getFavoriteFolderCreate() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.userSignatureUpdateOrNull: com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest?
  get() = if (hasUserSignatureUpdate()) getUserSignatureUpdate() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.favoriteForumListOrNull: com.bugenzhao.mnga.protos.service.FavoriteForumListRequest?
  get() = if (hasFavoriteForumList()) getFavoriteForumList() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.favoriteForumModifyOrNull: com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest?
  get() = if (hasFavoriteForumModify()) getFavoriteForumModify() else null

public val com.bugenzhao.mnga.protos.service.AsyncRequestOrBuilder.clockInStatsOrNull: com.bugenzhao.mnga.protos.service.ClockInStatsRequest?
  get() = if (hasClockInStats()) getClockInStats() else null

