// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface CacheResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CacheResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 items = 1;</code>
   * @return The items.
   */
  long getItems();

  /**
   * <code>uint64 total_size = 2;</code>
   * @return The totalSize.
   */
  long getTotalSize();
}
