// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface CacheRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CacheRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CacheType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.CacheType type = 1;</code>
   * @return The type.
   */
  com.bugenzhao.mnga.protos.datamodel.CacheType getType();

  /**
   * <code>.CacheOperation operation = 2;</code>
   * @return The enum numeric value on the wire for operation.
   */
  int getOperationValue();
  /**
   * <code>.CacheOperation operation = 2;</code>
   * @return The operation.
   */
  com.bugenzhao.mnga.protos.datamodel.CacheOperation getOperation();
}
