// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializeclockInRequest")
public inline fun clockInRequest(block: com.bugenzhao.mnga.protos.service.ClockInRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.ClockInRequest =
  com.bugenzhao.mnga.protos.service.ClockInRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.ClockInRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ClockInRequest`
 */
public object ClockInRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.ClockInRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.ClockInRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.ClockInRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.ClockInRequest.copy(block: `com.bugenzhao.mnga.protos.service`.ClockInRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.ClockInRequest =
  `com.bugenzhao.mnga.protos.service`.ClockInRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

