// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializeclockInStatsRequest")
public inline fun clockInStatsRequest(block: com.bugenzhao.mnga.protos.service.ClockInStatsRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.ClockInStatsRequest =
  com.bugenzhao.mnga.protos.service.ClockInStatsRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.ClockInStatsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ClockInStatsRequest`
 */
public object ClockInStatsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.ClockInStatsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.ClockInStatsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.ClockInStatsRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.ClockInStatsRequest.copy(block: `com.bugenzhao.mnga.protos.service`.ClockInStatsRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.ClockInStatsRequest =
  `com.bugenzhao.mnga.protos.service`.ClockInStatsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

