// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

/**
 * Protobuf type {@code ClockInResponse}
 */
@com.google.protobuf.Generated
public final class ClockInResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ClockInResponse)
    ClockInResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ClockInResponse");
  }
  // Use ClockInResponse.newBuilder() to construct.
  private ClockInResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ClockInResponse() {
    date_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_ClockInResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_ClockInResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_ClockInResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bugenzhao.mnga.protos.service.ClockInResponse.class, com.bugenzhao.mnga.protos.service.ClockInResponse.Builder.class);
  }

  public static final int DATE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object date_ = "";
  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  @java.lang.Override
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_FIRST_TIME_FIELD_NUMBER = 2;
  private boolean isFirstTime_ = false;
  /**
   * <code>bool is_first_time = 2;</code>
   * @return The isFirstTime.
   */
  @java.lang.Override
  public boolean getIsFirstTime() {
    return isFirstTime_;
  }

  public static final int CONTINUED_DAYS_FIELD_NUMBER = 3;
  private int continuedDays_ = 0;
  /**
   * <pre>
   * 签到统计（签到墙口径）：连续/累计签到天数、货币余额。
   * </pre>
   *
   * <code>int32 continued_days = 3;</code>
   * @return The continuedDays.
   */
  @java.lang.Override
  public int getContinuedDays() {
    return continuedDays_;
  }

  public static final int TOTAL_DAYS_FIELD_NUMBER = 4;
  private int totalDays_ = 0;
  /**
   * <code>int32 total_days = 4;</code>
   * @return The totalDays.
   */
  @java.lang.Override
  public int getTotalDays() {
    return totalDays_;
  }

  public static final int MONEY_FIELD_NUMBER = 5;
  private int money_ = 0;
  /**
   * <pre>
   * 货币总量，以铜币为最小单位（100 铜币 = 1 银币，100 银币 = 1 金币）。
   * </pre>
   *
   * <code>int32 money = 5;</code>
   * @return The money.
   */
  @java.lang.Override
  public int getMoney() {
    return money_;
  }

  public static final int MONEY_N_FIELD_NUMBER = 6;
  private int moneyN_ = 0;
  /**
   * <code>int32 money_n = 6;</code>
   * @return The moneyN.
   */
  @java.lang.Override
  public int getMoneyN() {
    return moneyN_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, date_);
    }
    if (isFirstTime_ != false) {
      output.writeBool(2, isFirstTime_);
    }
    if (continuedDays_ != 0) {
      output.writeInt32(3, continuedDays_);
    }
    if (totalDays_ != 0) {
      output.writeInt32(4, totalDays_);
    }
    if (money_ != 0) {
      output.writeInt32(5, money_);
    }
    if (moneyN_ != 0) {
      output.writeInt32(6, moneyN_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, date_);
    }
    if (isFirstTime_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isFirstTime_);
    }
    if (continuedDays_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, continuedDays_);
    }
    if (totalDays_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, totalDays_);
    }
    if (money_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, money_);
    }
    if (moneyN_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, moneyN_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bugenzhao.mnga.protos.service.ClockInResponse)) {
      return super.equals(obj);
    }
    com.bugenzhao.mnga.protos.service.ClockInResponse other = (com.bugenzhao.mnga.protos.service.ClockInResponse) obj;

    if (!getDate()
        .equals(other.getDate())) return false;
    if (getIsFirstTime()
        != other.getIsFirstTime()) return false;
    if (getContinuedDays()
        != other.getContinuedDays()) return false;
    if (getTotalDays()
        != other.getTotalDays()) return false;
    if (getMoney()
        != other.getMoney()) return false;
    if (getMoneyN()
        != other.getMoneyN()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (37 * hash) + IS_FIRST_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFirstTime());
    hash = (37 * hash) + CONTINUED_DAYS_FIELD_NUMBER;
    hash = (53 * hash) + getContinuedDays();
    hash = (37 * hash) + TOTAL_DAYS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalDays();
    hash = (37 * hash) + MONEY_FIELD_NUMBER;
    hash = (53 * hash) + getMoney();
    hash = (37 * hash) + MONEY_N_FIELD_NUMBER;
    hash = (53 * hash) + getMoneyN();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.service.ClockInResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bugenzhao.mnga.protos.service.ClockInResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClockInResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClockInResponse)
      com.bugenzhao.mnga.protos.service.ClockInResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_ClockInResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_ClockInResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bugenzhao.mnga.protos.service.ClockInResponse.class, com.bugenzhao.mnga.protos.service.ClockInResponse.Builder.class);
    }

    // Construct using com.bugenzhao.mnga.protos.service.ClockInResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      date_ = "";
      isFirstTime_ = false;
      continuedDays_ = 0;
      totalDays_ = 0;
      money_ = 0;
      moneyN_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_ClockInResponse_descriptor;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.ClockInResponse getDefaultInstanceForType() {
      return com.bugenzhao.mnga.protos.service.ClockInResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.ClockInResponse build() {
      com.bugenzhao.mnga.protos.service.ClockInResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.ClockInResponse buildPartial() {
      com.bugenzhao.mnga.protos.service.ClockInResponse result = new com.bugenzhao.mnga.protos.service.ClockInResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bugenzhao.mnga.protos.service.ClockInResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.date_ = date_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isFirstTime_ = isFirstTime_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.continuedDays_ = continuedDays_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalDays_ = totalDays_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.money_ = money_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.moneyN_ = moneyN_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bugenzhao.mnga.protos.service.ClockInResponse) {
        return mergeFrom((com.bugenzhao.mnga.protos.service.ClockInResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bugenzhao.mnga.protos.service.ClockInResponse other) {
      if (other == com.bugenzhao.mnga.protos.service.ClockInResponse.getDefaultInstance()) return this;
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIsFirstTime() != false) {
        setIsFirstTime(other.getIsFirstTime());
      }
      if (other.getContinuedDays() != 0) {
        setContinuedDays(other.getContinuedDays());
      }
      if (other.getTotalDays() != 0) {
        setTotalDays(other.getTotalDays());
      }
      if (other.getMoney() != 0) {
        setMoney(other.getMoney());
      }
      if (other.getMoneyN() != 0) {
        setMoneyN(other.getMoneyN());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              date_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isFirstTime_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              continuedDays_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalDays_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              money_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              moneyN_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object date_ = "";
    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      date_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      date_ = getDefaultInstance().getDate();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      date_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean isFirstTime_ ;
    /**
     * <code>bool is_first_time = 2;</code>
     * @return The isFirstTime.
     */
    @java.lang.Override
    public boolean getIsFirstTime() {
      return isFirstTime_;
    }
    /**
     * <code>bool is_first_time = 2;</code>
     * @param value The isFirstTime to set.
     * @return This builder for chaining.
     */
    public Builder setIsFirstTime(boolean value) {

      isFirstTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_first_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFirstTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isFirstTime_ = false;
      onChanged();
      return this;
    }

    private int continuedDays_ ;
    /**
     * <pre>
     * 签到统计（签到墙口径）：连续/累计签到天数、货币余额。
     * </pre>
     *
     * <code>int32 continued_days = 3;</code>
     * @return The continuedDays.
     */
    @java.lang.Override
    public int getContinuedDays() {
      return continuedDays_;
    }
    /**
     * <pre>
     * 签到统计（签到墙口径）：连续/累计签到天数、货币余额。
     * </pre>
     *
     * <code>int32 continued_days = 3;</code>
     * @param value The continuedDays to set.
     * @return This builder for chaining.
     */
    public Builder setContinuedDays(int value) {

      continuedDays_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 签到统计（签到墙口径）：连续/累计签到天数、货币余额。
     * </pre>
     *
     * <code>int32 continued_days = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContinuedDays() {
      bitField0_ = (bitField0_ & ~0x00000004);
      continuedDays_ = 0;
      onChanged();
      return this;
    }

    private int totalDays_ ;
    /**
     * <code>int32 total_days = 4;</code>
     * @return The totalDays.
     */
    @java.lang.Override
    public int getTotalDays() {
      return totalDays_;
    }
    /**
     * <code>int32 total_days = 4;</code>
     * @param value The totalDays to set.
     * @return This builder for chaining.
     */
    public Builder setTotalDays(int value) {

      totalDays_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_days = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalDays() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalDays_ = 0;
      onChanged();
      return this;
    }

    private int money_ ;
    /**
     * <pre>
     * 货币总量，以铜币为最小单位（100 铜币 = 1 银币，100 银币 = 1 金币）。
     * </pre>
     *
     * <code>int32 money = 5;</code>
     * @return The money.
     */
    @java.lang.Override
    public int getMoney() {
      return money_;
    }
    /**
     * <pre>
     * 货币总量，以铜币为最小单位（100 铜币 = 1 银币，100 银币 = 1 金币）。
     * </pre>
     *
     * <code>int32 money = 5;</code>
     * @param value The money to set.
     * @return This builder for chaining.
     */
    public Builder setMoney(int value) {

      money_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 货币总量，以铜币为最小单位（100 铜币 = 1 银币，100 银币 = 1 金币）。
     * </pre>
     *
     * <code>int32 money = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoney() {
      bitField0_ = (bitField0_ & ~0x00000010);
      money_ = 0;
      onChanged();
      return this;
    }

    private int moneyN_ ;
    /**
     * <code>int32 money_n = 6;</code>
     * @return The moneyN.
     */
    @java.lang.Override
    public int getMoneyN() {
      return moneyN_;
    }
    /**
     * <code>int32 money_n = 6;</code>
     * @param value The moneyN to set.
     * @return This builder for chaining.
     */
    public Builder setMoneyN(int value) {

      moneyN_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 money_n = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoneyN() {
      bitField0_ = (bitField0_ & ~0x00000020);
      moneyN_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ClockInResponse)
  }

  // @@protoc_insertion_point(class_scope:ClockInResponse)
  private static final com.bugenzhao.mnga.protos.service.ClockInResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bugenzhao.mnga.protos.service.ClockInResponse();
  }

  public static com.bugenzhao.mnga.protos.service.ClockInResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClockInResponse>
      PARSER = new com.google.protobuf.AbstractParser<ClockInResponse>() {
    @java.lang.Override
    public ClockInResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClockInResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClockInResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bugenzhao.mnga.protos.service.ClockInResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

