// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface FavoriteFolderCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FavoriteFolderCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool set_default = 2;</code>
   * @return The setDefault.
   */
  boolean getSetDefault();
}
