// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

/**
 * Protobuf type {@code FavoriteTopicListResponse}
 */
@com.google.protobuf.Generated
public final class FavoriteTopicListResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:FavoriteTopicListResponse)
    FavoriteTopicListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "FavoriteTopicListResponse");
  }
  // Use FavoriteTopicListResponse.newBuilder() to construct.
  private FavoriteTopicListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FavoriteTopicListResponse() {
    topics_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteTopicListResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteTopicListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteTopicListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse.class, com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse.Builder.class);
  }

  public static final int TOPICS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.bugenzhao.mnga.protos.datamodel.Topic> topics_;
  /**
   * <code>repeated .Topic topics = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.bugenzhao.mnga.protos.datamodel.Topic> getTopicsList() {
    return topics_;
  }
  /**
   * <code>repeated .Topic topics = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.TopicOrBuilder> 
      getTopicsOrBuilderList() {
    return topics_;
  }
  /**
   * <code>repeated .Topic topics = 1;</code>
   */
  @java.lang.Override
  public int getTopicsCount() {
    return topics_.size();
  }
  /**
   * <code>repeated .Topic topics = 1;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.Topic getTopics(int index) {
    return topics_.get(index);
  }
  /**
   * <code>repeated .Topic topics = 1;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.TopicOrBuilder getTopicsOrBuilder(
      int index) {
    return topics_.get(index);
  }

  public static final int PAGES_FIELD_NUMBER = 2;
  private int pages_ = 0;
  /**
   * <code>uint32 pages = 2;</code>
   * @return The pages.
   */
  @java.lang.Override
  public int getPages() {
    return pages_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < topics_.size(); i++) {
      output.writeMessage(1, topics_.get(i));
    }
    if (pages_ != 0) {
      output.writeUInt32(2, pages_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = topics_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(topics_.get(i));
          }
          size += 1 * count;
        }
    if (pages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, pages_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse)) {
      return super.equals(obj);
    }
    com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse other = (com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse) obj;

    if (!getTopicsList()
        .equals(other.getTopicsList())) return false;
    if (getPages()
        != other.getPages()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTopicsCount() > 0) {
      hash = (37 * hash) + TOPICS_FIELD_NUMBER;
      hash = (53 * hash) + getTopicsList().hashCode();
    }
    hash = (37 * hash) + PAGES_FIELD_NUMBER;
    hash = (53 * hash) + getPages();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FavoriteTopicListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FavoriteTopicListResponse)
      com.bugenzhao.mnga.protos.service.FavoriteTopicListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteTopicListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteTopicListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse.class, com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse.Builder.class);
    }

    // Construct using com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (topicsBuilder_ == null) {
        topics_ = java.util.Collections.emptyList();
      } else {
        topics_ = null;
        topicsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      pages_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteTopicListResponse_descriptor;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse getDefaultInstanceForType() {
      return com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse build() {
      com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse buildPartial() {
      com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse result = new com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse result) {
      if (topicsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          topics_ = java.util.Collections.unmodifiableList(topics_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.topics_ = topics_;
      } else {
        result.topics_ = topicsBuilder_.build();
      }
    }

    private void buildPartial0(com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pages_ = pages_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse) {
        return mergeFrom((com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse other) {
      if (other == com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse.getDefaultInstance()) return this;
      if (topicsBuilder_ == null) {
        if (!other.topics_.isEmpty()) {
          if (topics_.isEmpty()) {
            topics_ = other.topics_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTopicsIsMutable();
            topics_.addAll(other.topics_);
          }
          onChanged();
        }
      } else {
        if (!other.topics_.isEmpty()) {
          if (topicsBuilder_.isEmpty()) {
            topicsBuilder_.dispose();
            topicsBuilder_ = null;
            topics_ = other.topics_;
            bitField0_ = (bitField0_ & ~0x00000001);
            topicsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetTopicsFieldBuilder() : null;
          } else {
            topicsBuilder_.addAllMessages(other.topics_);
          }
        }
      }
      if (other.getPages() != 0) {
        setPages(other.getPages());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.bugenzhao.mnga.protos.datamodel.Topic m =
                  input.readMessage(
                      com.bugenzhao.mnga.protos.datamodel.Topic.parser(),
                      extensionRegistry);
              if (topicsBuilder_ == null) {
                ensureTopicsIsMutable();
                topics_.add(m);
              } else {
                topicsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              pages_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bugenzhao.mnga.protos.datamodel.Topic> topics_ =
      java.util.Collections.emptyList();
    private void ensureTopicsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        topics_ = new java.util.ArrayList<com.bugenzhao.mnga.protos.datamodel.Topic>(topics_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.Topic, com.bugenzhao.mnga.protos.datamodel.Topic.Builder, com.bugenzhao.mnga.protos.datamodel.TopicOrBuilder> topicsBuilder_;

    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public java.util.List<com.bugenzhao.mnga.protos.datamodel.Topic> getTopicsList() {
      if (topicsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(topics_);
      } else {
        return topicsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public int getTopicsCount() {
      if (topicsBuilder_ == null) {
        return topics_.size();
      } else {
        return topicsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Topic getTopics(int index) {
      if (topicsBuilder_ == null) {
        return topics_.get(index);
      } else {
        return topicsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder setTopics(
        int index, com.bugenzhao.mnga.protos.datamodel.Topic value) {
      if (topicsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicsIsMutable();
        topics_.set(index, value);
        onChanged();
      } else {
        topicsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder setTopics(
        int index, com.bugenzhao.mnga.protos.datamodel.Topic.Builder builderForValue) {
      if (topicsBuilder_ == null) {
        ensureTopicsIsMutable();
        topics_.set(index, builderForValue.build());
        onChanged();
      } else {
        topicsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder addTopics(com.bugenzhao.mnga.protos.datamodel.Topic value) {
      if (topicsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicsIsMutable();
        topics_.add(value);
        onChanged();
      } else {
        topicsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder addTopics(
        int index, com.bugenzhao.mnga.protos.datamodel.Topic value) {
      if (topicsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicsIsMutable();
        topics_.add(index, value);
        onChanged();
      } else {
        topicsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder addTopics(
        com.bugenzhao.mnga.protos.datamodel.Topic.Builder builderForValue) {
      if (topicsBuilder_ == null) {
        ensureTopicsIsMutable();
        topics_.add(builderForValue.build());
        onChanged();
      } else {
        topicsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder addTopics(
        int index, com.bugenzhao.mnga.protos.datamodel.Topic.Builder builderForValue) {
      if (topicsBuilder_ == null) {
        ensureTopicsIsMutable();
        topics_.add(index, builderForValue.build());
        onChanged();
      } else {
        topicsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder addAllTopics(
        java.lang.Iterable<? extends com.bugenzhao.mnga.protos.datamodel.Topic> values) {
      if (topicsBuilder_ == null) {
        ensureTopicsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, topics_);
        onChanged();
      } else {
        topicsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder clearTopics() {
      if (topicsBuilder_ == null) {
        topics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        topicsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public Builder removeTopics(int index) {
      if (topicsBuilder_ == null) {
        ensureTopicsIsMutable();
        topics_.remove(index);
        onChanged();
      } else {
        topicsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Topic.Builder getTopicsBuilder(
        int index) {
      return internalGetTopicsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.TopicOrBuilder getTopicsOrBuilder(
        int index) {
      if (topicsBuilder_ == null) {
        return topics_.get(index);  } else {
        return topicsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.TopicOrBuilder> 
         getTopicsOrBuilderList() {
      if (topicsBuilder_ != null) {
        return topicsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(topics_);
      }
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Topic.Builder addTopicsBuilder() {
      return internalGetTopicsFieldBuilder().addBuilder(
          com.bugenzhao.mnga.protos.datamodel.Topic.getDefaultInstance());
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Topic.Builder addTopicsBuilder(
        int index) {
      return internalGetTopicsFieldBuilder().addBuilder(
          index, com.bugenzhao.mnga.protos.datamodel.Topic.getDefaultInstance());
    }
    /**
     * <code>repeated .Topic topics = 1;</code>
     */
    public java.util.List<com.bugenzhao.mnga.protos.datamodel.Topic.Builder> 
         getTopicsBuilderList() {
      return internalGetTopicsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.Topic, com.bugenzhao.mnga.protos.datamodel.Topic.Builder, com.bugenzhao.mnga.protos.datamodel.TopicOrBuilder> 
        internalGetTopicsFieldBuilder() {
      if (topicsBuilder_ == null) {
        topicsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bugenzhao.mnga.protos.datamodel.Topic, com.bugenzhao.mnga.protos.datamodel.Topic.Builder, com.bugenzhao.mnga.protos.datamodel.TopicOrBuilder>(
                topics_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        topics_ = null;
      }
      return topicsBuilder_;
    }

    private int pages_ ;
    /**
     * <code>uint32 pages = 2;</code>
     * @return The pages.
     */
    @java.lang.Override
    public int getPages() {
      return pages_;
    }
    /**
     * <code>uint32 pages = 2;</code>
     * @param value The pages to set.
     * @return This builder for chaining.
     */
    public Builder setPages(int value) {

      pages_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 pages = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPages() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pages_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:FavoriteTopicListResponse)
  }

  // @@protoc_insertion_point(class_scope:FavoriteTopicListResponse)
  private static final com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse();
  }

  public static com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FavoriteTopicListResponse>
      PARSER = new com.google.protobuf.AbstractParser<FavoriteTopicListResponse>() {
    @java.lang.Override
    public FavoriteTopicListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FavoriteTopicListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FavoriteTopicListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bugenzhao.mnga.protos.service.FavoriteTopicListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

