// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializefavoriteFolderListRequest")
public inline fun favoriteFolderListRequest(block: com.bugenzhao.mnga.protos.service.FavoriteFolderListRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest =
  com.bugenzhao.mnga.protos.service.FavoriteFolderListRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `FavoriteFolderListRequest`
 */
public object FavoriteFolderListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest.copy(block: `com.bugenzhao.mnga.protos.service`.FavoriteFolderListRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.FavoriteFolderListRequest =
  `com.bugenzhao.mnga.protos.service`.FavoriteFolderListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

