// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

/**
 * Protobuf type {@code FavoriteForumModifyRequest}
 */
@com.google.protobuf.Generated
public final class FavoriteForumModifyRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:FavoriteForumModifyRequest)
    FavoriteForumModifyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "FavoriteForumModifyRequest");
  }
  // Use FavoriteForumModifyRequest.newBuilder() to construct.
  private FavoriteForumModifyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FavoriteForumModifyRequest() {
    operation_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteForumModifyRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteForumModifyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteForumModifyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.class, com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code FavoriteForumModifyRequest.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD = 0;</code>
     */
    ADD(0),
    /**
     * <code>DEL = 1;</code>
     */
    DEL(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "Operation");
    }
    /**
     * <code>ADD = 0;</code>
     */
    public static final int ADD_VALUE = 0;
    /**
     * <code>DEL = 1;</code>
     */
    public static final int DEL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operation valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Operation forNumber(int value) {
      switch (value) {
        case 0: return ADD;
        case 1: return DEL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.getDescriptor().getEnumType(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FavoriteForumModifyRequest.Operation)
  }

  private int bitField0_;
  public static final int OPERATION_FIELD_NUMBER = 1;
  private int operation_ = 0;
  /**
   * <code>.FavoriteForumModifyRequest.Operation operation = 1;</code>
   * @return The enum numeric value on the wire for operation.
   */
  @java.lang.Override public int getOperationValue() {
    return operation_;
  }
  /**
   * <code>.FavoriteForumModifyRequest.Operation operation = 1;</code>
   * @return The operation.
   */
  @java.lang.Override public com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation getOperation() {
    com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation result = com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation.forNumber(operation_);
    return result == null ? com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation.UNRECOGNIZED : result;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private com.bugenzhao.mnga.protos.datamodel.ForumId id_;
  /**
   * <code>.ForumId id = 2;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.ForumId id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.ForumId getId() {
    return id_ == null ? com.bugenzhao.mnga.protos.datamodel.ForumId.getDefaultInstance() : id_;
  }
  /**
   * <code>.ForumId id = 2;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.ForumIdOrBuilder getIdOrBuilder() {
    return id_ == null ? com.bugenzhao.mnga.protos.datamodel.ForumId.getDefaultInstance() : id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (operation_ != com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation.ADD.getNumber()) {
      output.writeEnum(1, operation_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getId());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (operation_ != com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation.ADD.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, operation_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getId());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest)) {
      return super.equals(obj);
    }
    com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest other = (com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest) obj;

    if (operation_ != other.operation_) return false;
    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + operation_;
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FavoriteForumModifyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FavoriteForumModifyRequest)
      com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteForumModifyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteForumModifyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.class, com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Builder.class);
    }

    // Construct using com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetIdFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      operation_ = 0;
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FavoriteForumModifyRequest_descriptor;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest getDefaultInstanceForType() {
      return com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest build() {
      com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest buildPartial() {
      com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest result = new com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.operation_ = operation_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest) {
        return mergeFrom((com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest other) {
      if (other == com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.getDefaultInstance()) return this;
      if (other.operation_ != 0) {
        setOperationValue(other.getOperationValue());
      }
      if (other.hasId()) {
        mergeId(other.getId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              operation_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int operation_ = 0;
    /**
     * <code>.FavoriteForumModifyRequest.Operation operation = 1;</code>
     * @return The enum numeric value on the wire for operation.
     */
    @java.lang.Override public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.FavoriteForumModifyRequest.Operation operation = 1;</code>
     * @param value The enum numeric value on the wire for operation to set.
     * @return This builder for chaining.
     */
    public Builder setOperationValue(int value) {
      operation_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.FavoriteForumModifyRequest.Operation operation = 1;</code>
     * @return The operation.
     */
    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation getOperation() {
      com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation result = com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation.forNumber(operation_);
      return result == null ? com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation.UNRECOGNIZED : result;
    }
    /**
     * <code>.FavoriteForumModifyRequest.Operation operation = 1;</code>
     * @param value The operation to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setOperation(com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest.Operation value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      operation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.FavoriteForumModifyRequest.Operation operation = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperation() {
      bitField0_ = (bitField0_ & ~0x00000001);
      operation_ = 0;
      onChanged();
      return this;
    }

    private com.bugenzhao.mnga.protos.datamodel.ForumId id_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.ForumId, com.bugenzhao.mnga.protos.datamodel.ForumId.Builder, com.bugenzhao.mnga.protos.datamodel.ForumIdOrBuilder> idBuilder_;
    /**
     * <code>.ForumId id = 2;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.ForumId id = 2;</code>
     * @return The id.
     */
    public com.bugenzhao.mnga.protos.datamodel.ForumId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.bugenzhao.mnga.protos.datamodel.ForumId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.ForumId id = 2;</code>
     */
    public Builder setId(com.bugenzhao.mnga.protos.datamodel.ForumId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ForumId id = 2;</code>
     */
    public Builder setId(
        com.bugenzhao.mnga.protos.datamodel.ForumId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ForumId id = 2;</code>
     */
    public Builder mergeId(com.bugenzhao.mnga.protos.datamodel.ForumId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          id_ != null &&
          id_ != com.bugenzhao.mnga.protos.datamodel.ForumId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      if (id_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ForumId id = 2;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ForumId id = 2;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.ForumId.Builder getIdBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.ForumId id = 2;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.ForumIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.bugenzhao.mnga.protos.datamodel.ForumId.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.ForumId id = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.ForumId, com.bugenzhao.mnga.protos.datamodel.ForumId.Builder, com.bugenzhao.mnga.protos.datamodel.ForumIdOrBuilder> 
        internalGetIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bugenzhao.mnga.protos.datamodel.ForumId, com.bugenzhao.mnga.protos.datamodel.ForumId.Builder, com.bugenzhao.mnga.protos.datamodel.ForumIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:FavoriteForumModifyRequest)
  }

  // @@protoc_insertion_point(class_scope:FavoriteForumModifyRequest)
  private static final com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest();
  }

  public static com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FavoriteForumModifyRequest>
      PARSER = new com.google.protobuf.AbstractParser<FavoriteForumModifyRequest>() {
    @java.lang.Override
    public FavoriteForumModifyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FavoriteForumModifyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FavoriteForumModifyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bugenzhao.mnga.protos.service.FavoriteForumModifyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

