// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface FavoriteFolderListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FavoriteFolderListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .FavoriteTopicFolder folders = 1;</code>
   */
  java.util.List<com.bugenzhao.mnga.protos.datamodel.FavoriteTopicFolder> 
      getFoldersList();
  /**
   * <code>repeated .FavoriteTopicFolder folders = 1;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.FavoriteTopicFolder getFolders(int index);
  /**
   * <code>repeated .FavoriteTopicFolder folders = 1;</code>
   */
  int getFoldersCount();
  /**
   * <code>repeated .FavoriteTopicFolder folders = 1;</code>
   */
  java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.FavoriteTopicFolderOrBuilder> 
      getFoldersOrBuilderList();
  /**
   * <code>repeated .FavoriteTopicFolder folders = 1;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.FavoriteTopicFolderOrBuilder getFoldersOrBuilder(
      int index);
}
