// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface FavoriteTopicListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FavoriteTopicListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>string folder_id = 2;</code>
   * @return The folderId.
   */
  java.lang.String getFolderId();
  /**
   * <code>string folder_id = 2;</code>
   * @return The bytes for folderId.
   */
  com.google.protobuf.ByteString
      getFolderIdBytes();
}
