// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializefavoriteForumListRequest")
public inline fun favoriteForumListRequest(block: com.bugenzhao.mnga.protos.service.FavoriteForumListRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.FavoriteForumListRequest =
  com.bugenzhao.mnga.protos.service.FavoriteForumListRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.FavoriteForumListRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `FavoriteForumListRequest`
 */
public object FavoriteForumListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.FavoriteForumListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.FavoriteForumListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.FavoriteForumListRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.FavoriteForumListRequest.copy(block: `com.bugenzhao.mnga.protos.service`.FavoriteForumListRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.FavoriteForumListRequest =
  `com.bugenzhao.mnga.protos.service`.FavoriteForumListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

