// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

/**
 * Protobuf type {@code FetchNotificationResponse}
 */
@com.google.protobuf.Generated
public final class FetchNotificationResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:FetchNotificationResponse)
    FetchNotificationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "FetchNotificationResponse");
  }
  // Use FetchNotificationResponse.newBuilder() to construct.
  private FetchNotificationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FetchNotificationResponse() {
    notis_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FetchNotificationResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FetchNotificationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bugenzhao.mnga.protos.service.Service.internal_static_FetchNotificationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bugenzhao.mnga.protos.service.FetchNotificationResponse.class, com.bugenzhao.mnga.protos.service.FetchNotificationResponse.Builder.class);
  }

  public static final int NOTIS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.bugenzhao.mnga.protos.datamodel.Notification> notis_;
  /**
   * <code>repeated .Notification notis = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.bugenzhao.mnga.protos.datamodel.Notification> getNotisList() {
    return notis_;
  }
  /**
   * <code>repeated .Notification notis = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.NotificationOrBuilder> 
      getNotisOrBuilderList() {
    return notis_;
  }
  /**
   * <code>repeated .Notification notis = 1;</code>
   */
  @java.lang.Override
  public int getNotisCount() {
    return notis_.size();
  }
  /**
   * <code>repeated .Notification notis = 1;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.Notification getNotis(int index) {
    return notis_.get(index);
  }
  /**
   * <code>repeated .Notification notis = 1;</code>
   */
  @java.lang.Override
  public com.bugenzhao.mnga.protos.datamodel.NotificationOrBuilder getNotisOrBuilder(
      int index) {
    return notis_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < notis_.size(); i++) {
      output.writeMessage(1, notis_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = notis_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(notis_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bugenzhao.mnga.protos.service.FetchNotificationResponse)) {
      return super.equals(obj);
    }
    com.bugenzhao.mnga.protos.service.FetchNotificationResponse other = (com.bugenzhao.mnga.protos.service.FetchNotificationResponse) obj;

    if (!getNotisList()
        .equals(other.getNotisList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNotisCount() > 0) {
      hash = (37 * hash) + NOTIS_FIELD_NUMBER;
      hash = (53 * hash) + getNotisList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bugenzhao.mnga.protos.service.FetchNotificationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FetchNotificationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FetchNotificationResponse)
      com.bugenzhao.mnga.protos.service.FetchNotificationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FetchNotificationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FetchNotificationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bugenzhao.mnga.protos.service.FetchNotificationResponse.class, com.bugenzhao.mnga.protos.service.FetchNotificationResponse.Builder.class);
    }

    // Construct using com.bugenzhao.mnga.protos.service.FetchNotificationResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (notisBuilder_ == null) {
        notis_ = java.util.Collections.emptyList();
      } else {
        notis_ = null;
        notisBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bugenzhao.mnga.protos.service.Service.internal_static_FetchNotificationResponse_descriptor;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FetchNotificationResponse getDefaultInstanceForType() {
      return com.bugenzhao.mnga.protos.service.FetchNotificationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FetchNotificationResponse build() {
      com.bugenzhao.mnga.protos.service.FetchNotificationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bugenzhao.mnga.protos.service.FetchNotificationResponse buildPartial() {
      com.bugenzhao.mnga.protos.service.FetchNotificationResponse result = new com.bugenzhao.mnga.protos.service.FetchNotificationResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.bugenzhao.mnga.protos.service.FetchNotificationResponse result) {
      if (notisBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          notis_ = java.util.Collections.unmodifiableList(notis_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.notis_ = notis_;
      } else {
        result.notis_ = notisBuilder_.build();
      }
    }

    private void buildPartial0(com.bugenzhao.mnga.protos.service.FetchNotificationResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bugenzhao.mnga.protos.service.FetchNotificationResponse) {
        return mergeFrom((com.bugenzhao.mnga.protos.service.FetchNotificationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bugenzhao.mnga.protos.service.FetchNotificationResponse other) {
      if (other == com.bugenzhao.mnga.protos.service.FetchNotificationResponse.getDefaultInstance()) return this;
      if (notisBuilder_ == null) {
        if (!other.notis_.isEmpty()) {
          if (notis_.isEmpty()) {
            notis_ = other.notis_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNotisIsMutable();
            notis_.addAll(other.notis_);
          }
          onChanged();
        }
      } else {
        if (!other.notis_.isEmpty()) {
          if (notisBuilder_.isEmpty()) {
            notisBuilder_.dispose();
            notisBuilder_ = null;
            notis_ = other.notis_;
            bitField0_ = (bitField0_ & ~0x00000001);
            notisBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetNotisFieldBuilder() : null;
          } else {
            notisBuilder_.addAllMessages(other.notis_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.bugenzhao.mnga.protos.datamodel.Notification m =
                  input.readMessage(
                      com.bugenzhao.mnga.protos.datamodel.Notification.parser(),
                      extensionRegistry);
              if (notisBuilder_ == null) {
                ensureNotisIsMutable();
                notis_.add(m);
              } else {
                notisBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bugenzhao.mnga.protos.datamodel.Notification> notis_ =
      java.util.Collections.emptyList();
    private void ensureNotisIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        notis_ = new java.util.ArrayList<com.bugenzhao.mnga.protos.datamodel.Notification>(notis_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.Notification, com.bugenzhao.mnga.protos.datamodel.Notification.Builder, com.bugenzhao.mnga.protos.datamodel.NotificationOrBuilder> notisBuilder_;

    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public java.util.List<com.bugenzhao.mnga.protos.datamodel.Notification> getNotisList() {
      if (notisBuilder_ == null) {
        return java.util.Collections.unmodifiableList(notis_);
      } else {
        return notisBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public int getNotisCount() {
      if (notisBuilder_ == null) {
        return notis_.size();
      } else {
        return notisBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Notification getNotis(int index) {
      if (notisBuilder_ == null) {
        return notis_.get(index);
      } else {
        return notisBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder setNotis(
        int index, com.bugenzhao.mnga.protos.datamodel.Notification value) {
      if (notisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotisIsMutable();
        notis_.set(index, value);
        onChanged();
      } else {
        notisBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder setNotis(
        int index, com.bugenzhao.mnga.protos.datamodel.Notification.Builder builderForValue) {
      if (notisBuilder_ == null) {
        ensureNotisIsMutable();
        notis_.set(index, builderForValue.build());
        onChanged();
      } else {
        notisBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder addNotis(com.bugenzhao.mnga.protos.datamodel.Notification value) {
      if (notisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotisIsMutable();
        notis_.add(value);
        onChanged();
      } else {
        notisBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder addNotis(
        int index, com.bugenzhao.mnga.protos.datamodel.Notification value) {
      if (notisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotisIsMutable();
        notis_.add(index, value);
        onChanged();
      } else {
        notisBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder addNotis(
        com.bugenzhao.mnga.protos.datamodel.Notification.Builder builderForValue) {
      if (notisBuilder_ == null) {
        ensureNotisIsMutable();
        notis_.add(builderForValue.build());
        onChanged();
      } else {
        notisBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder addNotis(
        int index, com.bugenzhao.mnga.protos.datamodel.Notification.Builder builderForValue) {
      if (notisBuilder_ == null) {
        ensureNotisIsMutable();
        notis_.add(index, builderForValue.build());
        onChanged();
      } else {
        notisBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder addAllNotis(
        java.lang.Iterable<? extends com.bugenzhao.mnga.protos.datamodel.Notification> values) {
      if (notisBuilder_ == null) {
        ensureNotisIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, notis_);
        onChanged();
      } else {
        notisBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder clearNotis() {
      if (notisBuilder_ == null) {
        notis_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        notisBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public Builder removeNotis(int index) {
      if (notisBuilder_ == null) {
        ensureNotisIsMutable();
        notis_.remove(index);
        onChanged();
      } else {
        notisBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Notification.Builder getNotisBuilder(
        int index) {
      return internalGetNotisFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.NotificationOrBuilder getNotisOrBuilder(
        int index) {
      if (notisBuilder_ == null) {
        return notis_.get(index);  } else {
        return notisBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.NotificationOrBuilder> 
         getNotisOrBuilderList() {
      if (notisBuilder_ != null) {
        return notisBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(notis_);
      }
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Notification.Builder addNotisBuilder() {
      return internalGetNotisFieldBuilder().addBuilder(
          com.bugenzhao.mnga.protos.datamodel.Notification.getDefaultInstance());
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public com.bugenzhao.mnga.protos.datamodel.Notification.Builder addNotisBuilder(
        int index) {
      return internalGetNotisFieldBuilder().addBuilder(
          index, com.bugenzhao.mnga.protos.datamodel.Notification.getDefaultInstance());
    }
    /**
     * <code>repeated .Notification notis = 1;</code>
     */
    public java.util.List<com.bugenzhao.mnga.protos.datamodel.Notification.Builder> 
         getNotisBuilderList() {
      return internalGetNotisFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bugenzhao.mnga.protos.datamodel.Notification, com.bugenzhao.mnga.protos.datamodel.Notification.Builder, com.bugenzhao.mnga.protos.datamodel.NotificationOrBuilder> 
        internalGetNotisFieldBuilder() {
      if (notisBuilder_ == null) {
        notisBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bugenzhao.mnga.protos.datamodel.Notification, com.bugenzhao.mnga.protos.datamodel.Notification.Builder, com.bugenzhao.mnga.protos.datamodel.NotificationOrBuilder>(
                notis_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        notis_ = null;
      }
      return notisBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:FetchNotificationResponse)
  }

  // @@protoc_insertion_point(class_scope:FetchNotificationResponse)
  private static final com.bugenzhao.mnga.protos.service.FetchNotificationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bugenzhao.mnga.protos.service.FetchNotificationResponse();
  }

  public static com.bugenzhao.mnga.protos.service.FetchNotificationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchNotificationResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchNotificationResponse>() {
    @java.lang.Override
    public FetchNotificationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FetchNotificationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchNotificationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bugenzhao.mnga.protos.service.FetchNotificationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

