// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializeforumListRequest")
public inline fun forumListRequest(block: com.bugenzhao.mnga.protos.service.ForumListRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.ForumListRequest =
  com.bugenzhao.mnga.protos.service.ForumListRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.ForumListRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `ForumListRequest`
 */
public object ForumListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.ForumListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.ForumListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.ForumListRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.ForumListRequest.copy(block: `com.bugenzhao.mnga.protos.service`.ForumListRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.ForumListRequest =
  `com.bugenzhao.mnga.protos.service`.ForumListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

