// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface HotTopicListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HotTopicListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ForumId id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.ForumId id = 1;</code>
   * @return The id.
   */
  com.bugenzhao.mnga.protos.datamodel.ForumId getId();
  /**
   * <code>.ForumId id = 1;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.ForumIdOrBuilder getIdOrBuilder();

  /**
   * <pre>
   * Only see topics posted in this date range.
   * </pre>
   *
   * <code>.HotTopicListRequest.DateRange range = 2;</code>
   * @return The enum numeric value on the wire for range.
   */
  int getRangeValue();
  /**
   * <pre>
   * Only see topics posted in this date range.
   * </pre>
   *
   * <code>.HotTopicListRequest.DateRange range = 2;</code>
   * @return The range.
   */
  com.bugenzhao.mnga.protos.service.HotTopicListRequest.DateRange getRange();

  /**
   * <pre>
   * Maximum page of topics to collect.
   * </pre>
   *
   * <code>optional uint32 fetch_page_limit = 3;</code>
   * @return Whether the fetchPageLimit field is set.
   */
  boolean hasFetchPageLimit();
  /**
   * <pre>
   * Maximum page of topics to collect.
   * </pre>
   *
   * <code>optional uint32 fetch_page_limit = 3;</code>
   * @return The fetchPageLimit.
   */
  int getFetchPageLimit();

  /**
   * <code>optional uint64 limit = 4;</code>
   * @return Whether the limit field is set.
   */
  boolean hasLimit();
  /**
   * <code>optional uint64 limit = 4;</code>
   * @return The limit.
   */
  long getLimit();
}
