// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializemockApi")
public inline fun mockApi(block: com.bugenzhao.mnga.protos.service.MockApiKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.MockApi =
  com.bugenzhao.mnga.protos.service.MockApiKt.Dsl._create(com.bugenzhao.mnga.protos.service.MockApi.newBuilder()).apply { block() }._build()
/**
 * ```
 *
 * MNGA-only mock APIs.
 * ```
 *
 * Protobuf type `MockApi`
 */
public object MockApiKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.MockApi.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.MockApi.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.MockApi = _builder.build()

    /**
     * `.MockApi.TopicList topic_list = 1;`
     */
    public var topicList: com.bugenzhao.mnga.protos.service.MockApi.TopicList
      @kotlin.jvm.JvmName("getTopicList")
        get() = _builder.topicList
      @kotlin.jvm.JvmName("setTopicList")
        set(value) {
        _builder.topicList = value
      }
    /**
     * `.MockApi.TopicList topic_list = 1;`
     */
    public fun clearTopicList() {
      _builder.clearTopicList()
    }
    /**
     * `.MockApi.TopicList topic_list = 1;`
     * @return Whether the topicList field is set.
     */
    public fun hasTopicList(): kotlin.Boolean {
      return _builder.hasTopicList()
    }

    /**
     * `.MockApi.TopicDetails topic_details = 2;`
     */
    public var topicDetails: com.bugenzhao.mnga.protos.service.MockApi.TopicDetails
      @kotlin.jvm.JvmName("getTopicDetails")
        get() = _builder.topicDetails
      @kotlin.jvm.JvmName("setTopicDetails")
        set(value) {
        _builder.topicDetails = value
      }
    /**
     * `.MockApi.TopicDetails topic_details = 2;`
     */
    public fun clearTopicDetails() {
      _builder.clearTopicDetails()
    }
    /**
     * `.MockApi.TopicDetails topic_details = 2;`
     * @return Whether the topicDetails field is set.
     */
    public fun hasTopicDetails(): kotlin.Boolean {
      return _builder.hasTopicDetails()
    }
    public val valueCase: com.bugenzhao.mnga.protos.service.MockApi.ValueCase
    @kotlin.jvm.JvmName("getValueCase")
      get() = _builder.getValueCase()

    public fun clearValue() {
      _builder.clearValue()
    }
  }
  @kotlin.jvm.JvmName("-initializetopicList")
  public inline fun topicList(block: com.bugenzhao.mnga.protos.service.MockApiKt.TopicListKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.MockApi.TopicList =
    com.bugenzhao.mnga.protos.service.MockApiKt.TopicListKt.Dsl._create(com.bugenzhao.mnga.protos.service.MockApi.TopicList.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `MockApi.TopicList`
   */
  public object TopicListKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.bugenzhao.mnga.protos.service.MockApi.TopicList.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: com.bugenzhao.mnga.protos.service.MockApi.TopicList.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): com.bugenzhao.mnga.protos.service.MockApi.TopicList = _builder.build()

      /**
       * `string id = 1;`
       */
      public var id: kotlin.String
        @kotlin.jvm.JvmName("getId")
          get() = _builder.id
        @kotlin.jvm.JvmName("setId")
          set(value) {
          _builder.id = value
        }
      /**
       * `string id = 1;`
       */
      public fun clearId() {
        _builder.clearId()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializetopicDetails")
  public inline fun topicDetails(block: com.bugenzhao.mnga.protos.service.MockApiKt.TopicDetailsKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.MockApi.TopicDetails =
    com.bugenzhao.mnga.protos.service.MockApiKt.TopicDetailsKt.Dsl._create(com.bugenzhao.mnga.protos.service.MockApi.TopicDetails.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `MockApi.TopicDetails`
   */
  public object TopicDetailsKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.bugenzhao.mnga.protos.service.MockApi.TopicDetails.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: com.bugenzhao.mnga.protos.service.MockApi.TopicDetails.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): com.bugenzhao.mnga.protos.service.MockApi.TopicDetails = _builder.build()

      /**
       * `string id = 1;`
       */
      public var id: kotlin.String
        @kotlin.jvm.JvmName("getId")
          get() = _builder.id
        @kotlin.jvm.JvmName("setId")
          set(value) {
          _builder.id = value
        }
      /**
       * `string id = 1;`
       */
      public fun clearId() {
        _builder.clearId()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.MockApi.copy(block: `com.bugenzhao.mnga.protos.service`.MockApiKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.MockApi =
  `com.bugenzhao.mnga.protos.service`.MockApiKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.MockApi.TopicList.copy(block: `com.bugenzhao.mnga.protos.service`.MockApiKt.TopicListKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.MockApi.TopicList =
  `com.bugenzhao.mnga.protos.service`.MockApiKt.TopicListKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.MockApi.TopicDetails.copy(block: `com.bugenzhao.mnga.protos.service`.MockApiKt.TopicDetailsKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.MockApi.TopicDetails =
  `com.bugenzhao.mnga.protos.service`.MockApiKt.TopicDetailsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.service.MockApiOrBuilder.topicListOrNull: com.bugenzhao.mnga.protos.service.MockApi.TopicList?
  get() = if (hasTopicList()) getTopicList() else null

public val com.bugenzhao.mnga.protos.service.MockApiOrBuilder.topicDetailsOrNull: com.bugenzhao.mnga.protos.service.MockApi.TopicDetails?
  get() = if (hasTopicDetails()) getTopicDetails() else null

