// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface PostReplyFetchContentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostReplyFetchContentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * Used for topics.
   * </pre>
   *
   * <code>optional string subject = 2;</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <pre>
   * Used for topics.
   * </pre>
   *
   * <code>optional string subject = 2;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <pre>
   * Used for topics.
   * </pre>
   *
   * <code>optional string subject = 2;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <pre>
   * Extra info to keep and pass verbatim.
   * </pre>
   *
   * <code>.PostReplyVerbatim verbatim = 3;</code>
   * @return Whether the verbatim field is set.
   */
  boolean hasVerbatim();
  /**
   * <pre>
   * Extra info to keep and pass verbatim.
   * </pre>
   *
   * <code>.PostReplyVerbatim verbatim = 3;</code>
   * @return The verbatim.
   */
  com.bugenzhao.mnga.protos.datamodel.PostReplyVerbatim getVerbatim();
  /**
   * <pre>
   * Extra info to keep and pass verbatim.
   * </pre>
   *
   * <code>.PostReplyVerbatim verbatim = 3;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.PostReplyVerbatimOrBuilder getVerbatimOrBuilder();
}
