// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializepostReplyRequest")
public inline fun postReplyRequest(block: com.bugenzhao.mnga.protos.service.PostReplyRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.PostReplyRequest =
  com.bugenzhao.mnga.protos.service.PostReplyRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.PostReplyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `PostReplyRequest`
 */
public object PostReplyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.PostReplyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.PostReplyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.PostReplyRequest = _builder.build()

    /**
     * `.PostReplyAction action = 1;`
     */
    public var action: com.bugenzhao.mnga.protos.datamodel.PostReplyAction
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * `.PostReplyAction action = 1;`
     */
    public fun clearAction() {
      _builder.clearAction()
    }
    /**
     * `.PostReplyAction action = 1;`
     * @return Whether the action field is set.
     */
    public fun hasAction(): kotlin.Boolean {
      return _builder.hasAction()
    }

    public val PostReplyRequestKt.Dsl.actionOrNull: com.bugenzhao.mnga.protos.datamodel.PostReplyAction?
      get() = _builder.actionOrNull

    /**
     * `string content = 2;`
     */
    public var content: kotlin.String
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `string content = 2;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }

    /**
     * `optional string subject = 3;`
     */
    public var subject: kotlin.String
      @kotlin.jvm.JvmName("getSubject")
        get() = _builder.subject
      @kotlin.jvm.JvmName("setSubject")
        set(value) {
        _builder.subject = value
      }
    /**
     * `optional string subject = 3;`
     */
    public fun clearSubject() {
      _builder.clearSubject()
    }
    /**
     * `optional string subject = 3;`
     * @return Whether the subject field is set.
     */
    public fun hasSubject(): kotlin.Boolean {
      return _builder.hasSubject()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AttachmentsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .PostAttachment attachments = 4;`
     */
     public val attachments: com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.PostAttachment, AttachmentsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.attachmentsList
      )
    /**
     * `repeated .PostAttachment attachments = 4;`
     * @param value The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.PostAttachment, AttachmentsProxy>.add(value: com.bugenzhao.mnga.protos.datamodel.PostAttachment) {
      _builder.addAttachments(value)
    }
    /**
     * `repeated .PostAttachment attachments = 4;`
     * @param value The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAttachments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.PostAttachment, AttachmentsProxy>.plusAssign(value: com.bugenzhao.mnga.protos.datamodel.PostAttachment) {
      add(value)
    }
    /**
     * `repeated .PostAttachment attachments = 4;`
     * @param values The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.PostAttachment, AttachmentsProxy>.addAll(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.PostAttachment>) {
      _builder.addAllAttachments(values)
    }
    /**
     * `repeated .PostAttachment attachments = 4;`
     * @param values The attachments to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAttachments")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.PostAttachment, AttachmentsProxy>.plusAssign(values: kotlin.collections.Iterable<com.bugenzhao.mnga.protos.datamodel.PostAttachment>) {
      addAll(values)
    }
    /**
     * `repeated .PostAttachment attachments = 4;`
     * @param index The index to set the value at.
     * @param value The attachments to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAttachments")
    public operator fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.PostAttachment, AttachmentsProxy>.set(index: kotlin.Int, value: com.bugenzhao.mnga.protos.datamodel.PostAttachment) {
      _builder.setAttachments(index, value)
    }
    /**
     * `repeated .PostAttachment attachments = 4;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearAttachments")
    public fun com.google.protobuf.kotlin.DslList<com.bugenzhao.mnga.protos.datamodel.PostAttachment, AttachmentsProxy>.clear() {
      _builder.clearAttachments()
    }

    /**
     * ```
     * Whether to post as anonymous identity.
     * ```
     *
     * `bool anonymous = 5;`
     */
    public var anonymous: kotlin.Boolean
      @kotlin.jvm.JvmName("getAnonymous")
        get() = _builder.anonymous
      @kotlin.jvm.JvmName("setAnonymous")
        set(value) {
        _builder.anonymous = value
      }
    /**
     * ```
     * Whether to post as anonymous identity.
     * ```
     *
     * `bool anonymous = 5;`
     */
    public fun clearAnonymous() {
      _builder.clearAnonymous()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.PostReplyRequest.copy(block: `com.bugenzhao.mnga.protos.service`.PostReplyRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.PostReplyRequest =
  `com.bugenzhao.mnga.protos.service`.PostReplyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.service.PostReplyRequestOrBuilder.actionOrNull: com.bugenzhao.mnga.protos.datamodel.PostReplyAction?
  get() = if (hasAction()) getAction() else null

