// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializesetRequestOptionRequest")
public inline fun setRequestOptionRequest(block: com.bugenzhao.mnga.protos.service.SetRequestOptionRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.SetRequestOptionRequest =
  com.bugenzhao.mnga.protos.service.SetRequestOptionRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.SetRequestOptionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `SetRequestOptionRequest`
 */
public object SetRequestOptionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.SetRequestOptionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.SetRequestOptionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.SetRequestOptionRequest = _builder.build()

    /**
     * `.RequestOption option = 1;`
     */
    public var option: com.bugenzhao.mnga.protos.datamodel.RequestOption
      @kotlin.jvm.JvmName("getOption")
        get() = _builder.option
      @kotlin.jvm.JvmName("setOption")
        set(value) {
        _builder.option = value
      }
    /**
     * `.RequestOption option = 1;`
     */
    public fun clearOption() {
      _builder.clearOption()
    }
    /**
     * `.RequestOption option = 1;`
     * @return Whether the option field is set.
     */
    public fun hasOption(): kotlin.Boolean {
      return _builder.hasOption()
    }

    public val SetRequestOptionRequestKt.Dsl.optionOrNull: com.bugenzhao.mnga.protos.datamodel.RequestOption?
      get() = _builder.optionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.SetRequestOptionRequest.copy(block: `com.bugenzhao.mnga.protos.service`.SetRequestOptionRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.SetRequestOptionRequest =
  `com.bugenzhao.mnga.protos.service`.SetRequestOptionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.bugenzhao.mnga.protos.service.SetRequestOptionRequestOrBuilder.optionOrNull: com.bugenzhao.mnga.protos.datamodel.RequestOption?
  get() = if (hasOption()) getOption() else null

