// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface ShortMessageDetailsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShortMessageDetailsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ShortMessagePost posts = 1;</code>
   */
  java.util.List<com.bugenzhao.mnga.protos.datamodel.ShortMessagePost> 
      getPostsList();
  /**
   * <code>repeated .ShortMessagePost posts = 1;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.ShortMessagePost getPosts(int index);
  /**
   * <code>repeated .ShortMessagePost posts = 1;</code>
   */
  int getPostsCount();
  /**
   * <code>repeated .ShortMessagePost posts = 1;</code>
   */
  java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.ShortMessagePostOrBuilder> 
      getPostsOrBuilderList();
  /**
   * <code>repeated .ShortMessagePost posts = 1;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.ShortMessagePostOrBuilder getPostsOrBuilder(
      int index);

  /**
   * <code>uint32 pages = 2;</code>
   * @return The pages.
   */
  int getPages();

  /**
   * <code>repeated .User users = 3;</code>
   */
  java.util.List<com.bugenzhao.mnga.protos.datamodel.User> 
      getUsersList();
  /**
   * <code>repeated .User users = 3;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.User getUsers(int index);
  /**
   * <code>repeated .User users = 3;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .User users = 3;</code>
   */
  java.util.List<? extends com.bugenzhao.mnga.protos.datamodel.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .User users = 3;</code>
   */
  com.bugenzhao.mnga.protos.datamodel.UserOrBuilder getUsersOrBuilder(
      int index);
}
