// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface SubforumFilterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubforumFilterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SubforumFilterRequest.Operation operation = 1;</code>
   * @return The enum numeric value on the wire for operation.
   */
  int getOperationValue();
  /**
   * <code>.SubforumFilterRequest.Operation operation = 1;</code>
   * @return The operation.
   */
  com.bugenzhao.mnga.protos.service.SubforumFilterRequest.Operation getOperation();

  /**
   * <pre>
   * ID of the parent forum.
   * </pre>
   *
   * <code>string forum_id = 2;</code>
   * @return The forumId.
   */
  java.lang.String getForumId();
  /**
   * <pre>
   * ID of the parent forum.
   * </pre>
   *
   * <code>string forum_id = 2;</code>
   * @return The bytes for forumId.
   */
  com.google.protobuf.ByteString
      getForumIdBytes();

  /**
   * <pre>
   * See `Subforum.filter_id`
   * </pre>
   *
   * <code>string subforum_filter_id = 3;</code>
   * @return The subforumFilterId.
   */
  java.lang.String getSubforumFilterId();
  /**
   * <pre>
   * See `Subforum.filter_id`
   * </pre>
   *
   * <code>string subforum_filter_id = 3;</code>
   * @return The bytes for subforumFilterId.
   */
  com.google.protobuf.ByteString
      getSubforumFilterIdBytes();
}
