// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializesubforumFilterRequest")
public inline fun subforumFilterRequest(block: com.bugenzhao.mnga.protos.service.SubforumFilterRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.SubforumFilterRequest =
  com.bugenzhao.mnga.protos.service.SubforumFilterRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.SubforumFilterRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `SubforumFilterRequest`
 */
public object SubforumFilterRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.SubforumFilterRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.SubforumFilterRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.SubforumFilterRequest = _builder.build()

    /**
     * `.SubforumFilterRequest.Operation operation = 1;`
     */
    public var operation: com.bugenzhao.mnga.protos.service.SubforumFilterRequest.Operation
      @kotlin.jvm.JvmName("getOperation")
        get() = _builder.operation
      @kotlin.jvm.JvmName("setOperation")
        set(value) {
        _builder.operation = value
      }
    public var operationValue: kotlin.Int
      @kotlin.jvm.JvmName("getOperationValue")
        get() = _builder.operationValue
      @kotlin.jvm.JvmName("setOperationValue")
        set(value) {
        _builder.operationValue = value
      }
    /**
     * `.SubforumFilterRequest.Operation operation = 1;`
     */
    public fun clearOperation() {
      _builder.clearOperation()
    }

    /**
     * ```
     * ID of the parent forum.
     * ```
     *
     * `string forum_id = 2;`
     */
    public var forumId: kotlin.String
      @kotlin.jvm.JvmName("getForumId")
        get() = _builder.forumId
      @kotlin.jvm.JvmName("setForumId")
        set(value) {
        _builder.forumId = value
      }
    /**
     * ```
     * ID of the parent forum.
     * ```
     *
     * `string forum_id = 2;`
     */
    public fun clearForumId() {
      _builder.clearForumId()
    }

    /**
     * ```
     * See `Subforum.filter_id`
     * ```
     *
     * `string subforum_filter_id = 3;`
     */
    public var subforumFilterId: kotlin.String
      @kotlin.jvm.JvmName("getSubforumFilterId")
        get() = _builder.subforumFilterId
      @kotlin.jvm.JvmName("setSubforumFilterId")
        set(value) {
        _builder.subforumFilterId = value
      }
    /**
     * ```
     * See `Subforum.filter_id`
     * ```
     *
     * `string subforum_filter_id = 3;`
     */
    public fun clearSubforumFilterId() {
      _builder.clearSubforumFilterId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.SubforumFilterRequest.copy(block: `com.bugenzhao.mnga.protos.service`.SubforumFilterRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.SubforumFilterRequest =
  `com.bugenzhao.mnga.protos.service`.SubforumFilterRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

