// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface SubjectParseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubjectParseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string raw = 1;</code>
   * @return The raw.
   */
  java.lang.String getRaw();
  /**
   * <code>string raw = 1;</code>
   * @return The bytes for raw.
   */
  com.google.protobuf.ByteString
      getRawBytes();
}
