// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto
// Protobuf Java Version: 4.35.1

package com.bugenzhao.mnga.protos.service;

@com.google.protobuf.Generated
public interface TopicFavorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TopicFavorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether `folder_ids` is non-empty.
   * </pre>
   *
   * <code>bool is_favored = 1;</code>
   * @return The isFavored.
   */
  boolean getIsFavored();

  /**
   * <pre>
   * IDs of the favorite folders that the topic is in.
   * </pre>
   *
   * <code>repeated string folder_ids = 2;</code>
   * @return A list containing the folderIds.
   */
  java.util.List<java.lang.String>
      getFolderIdsList();
  /**
   * <pre>
   * IDs of the favorite folders that the topic is in.
   * </pre>
   *
   * <code>repeated string folder_ids = 2;</code>
   * @return The count of folderIds.
   */
  int getFolderIdsCount();
  /**
   * <pre>
   * IDs of the favorite folders that the topic is in.
   * </pre>
   *
   * <code>repeated string folder_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The folderIds at the given index.
   */
  java.lang.String getFolderIds(int index);
  /**
   * <pre>
   * IDs of the favorite folders that the topic is in.
   * </pre>
   *
   * <code>repeated string folder_ids = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the folderIds at the given index.
   */
  com.google.protobuf.ByteString
      getFolderIdsBytes(int index);
}
