// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializeupdateTopicProgressResponse")
public inline fun updateTopicProgressResponse(block: com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponseKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponse =
  com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponseKt.Dsl._create(com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `UpdateTopicProgressResponse`
 */
public object UpdateTopicProgressResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponse.copy(block: `com.bugenzhao.mnga.protos.service`.UpdateTopicProgressResponseKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.UpdateTopicProgressResponse =
  `com.bugenzhao.mnga.protos.service`.UpdateTopicProgressResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

