// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.bugenzhao.mnga.protos.service;

@kotlin.jvm.JvmName("-initializeuserSignatureUpdateRequest")
public inline fun userSignatureUpdateRequest(block: com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest =
  com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequestKt.Dsl._create(com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `UserSignatureUpdateRequest`
 */
public object UserSignatureUpdateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest = _builder.build()

    /**
     * `string signature = 1;`
     */
    public var signature: kotlin.String
      @kotlin.jvm.JvmName("getSignature")
        get() = _builder.signature
      @kotlin.jvm.JvmName("setSignature")
        set(value) {
        _builder.signature = value
      }
    /**
     * `string signature = 1;`
     */
    public fun clearSignature() {
      _builder.clearSignature()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest.copy(block: `com.bugenzhao.mnga.protos.service`.UserSignatureUpdateRequestKt.Dsl.() -> kotlin.Unit): com.bugenzhao.mnga.protos.service.UserSignatureUpdateRequest =
  `com.bugenzhao.mnga.protos.service`.UserSignatureUpdateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

